import { useEffect, useRef, useState } from "react";
import AuthModal from "../../../components/AuthModal";
import { supabase } from "../../../lib/supabaseClient";
import { MENU_PHOTO_AUTH_REQUIRED, uploadMenuItemImage, retuneMenuItemImage, reanalyzeMenuItemImage } from "./menuItemImageStorage";
import { getCurrentDraftDesign } from "./draftSession";
import { resolveMenuPhotoProfile, menuPhotoProfileDescription, menuPhotoProfileLabel } from "../domain/menuPhotoProfiles";
import MenuPhotoReviewCompare from "./MenuPhotoReviewCompare";
import "./MenuStudioItemPhotoField.css";

const COPY = {
  en:{label:"Dish photo",intro:"Use a real photo. Beyond will clean it up and match it to your menu.",take:"Take photo",choose:"Choose from phone",replace:"Replace",remove:"Remove",signIn:"Sign in to add photo",authRequired:"Sign in to Beyond to upload and save menu photos.",uploading:"Making your photo menu-ready…",drop:"Drop a food photo here",empty:"Add a real photo of this dish",error:"Photo upload failed",standard:"Beyond photo check",original:"Original",enhanced:"Enhanced",theme:"Menu style",recommended:"Recommended",currentMenu:"Matches",natural:"The dish stays real — Beyond only improves presentation.",themeSafe:"This version follows your menu's saved photo style without changing the dish.",retune:"Match menu style",retuning:"Matching style…",themeOutdated:"Your menu style changed. Update this photo to match it.",excellent:"Excellent",good:"Looks good",needs_improvement:"Could improve",low_quality:"Try another photo",framing:"Choose what stays in focus",framingHint:"Move the target to the most important part of the dish.",adjustFraming:"Adjust crop focus",doneFraming:"Done",centerFraming:"Center",analyzedOnce:"Smart photo",cached:"Ready to reuse across menu designs",reanalyze:"Refresh",reanalyzing:"Refreshing…",reanalyzeHint:"Only refresh if the source photo changed.",step1:"1 · Add",step2:"2 · Beyond improves",step3:"3 · Pick your look",tip:"Best results: photograph the whole plate in good light.",processingTitle:"Beyond is preparing your photo",processingText:"Checking quality, improving the image and matching your menu style."},
  he:{label:"תמונת המנה",intro:"צלמו את המנה האמיתית. Beyond ישפר את התמונה ויתאים אותה לסגנון התפריט.",take:"צילום עכשיו",choose:"בחירה מהטלפון",replace:"החלפה",remove:"הסרה",signIn:"התחברות להוספת תמונה",authRequired:"יש להתחבר ל-Beyond כדי להעלות ולשמור תמונות בתפריט.",uploading:"מכין את התמונה לתפריט…",drop:"שחררו כאן תמונת מנה",empty:"הוסיפו תמונה אמיתית של המנה",error:"העלאת התמונה נכשלה",standard:"בדיקת התמונה של Beyond",original:"מקור",enhanced:"משופר",theme:"סגנון התפריט",recommended:"מומלץ",currentMenu:"מתאים ל",natural:"המנה נשארת אמיתית — Beyond משפר רק את ההצגה שלה.",themeSafe:"הגרסה הזו מותאמת לסגנון התמונות של התפריט בלי לשנות את המנה.",retune:"התאמה לסגנון התפריט",retuning:"מתאים סגנון…",themeOutdated:"סגנון התפריט השתנה. אפשר לעדכן את התמונה כך שתתאים.",excellent:"מצוין",good:"נראה טוב",needs_improvement:"אפשר לשפר",low_quality:"כדאי לצלם שוב",framing:"בחרו מה יישאר במרכז",framingHint:"הזיזו את הסמן לחלק החשוב ביותר במנה.",adjustFraming:"התאמת מוקד",doneFraming:"סיום",centerFraming:"מרכז",analyzedOnce:"תמונה חכמה",cached:"מוכנה לשימוש חוזר בכל עיצובי התפריט",reanalyze:"רענון",reanalyzing:"מרענן…",reanalyzeHint:"רעננו רק אם תמונת המקור השתנתה.",step1:"1 · מוסיפים",step2:"2 · Beyond משפר",step3:"3 · בוחרים מראה",tip:"לתוצאה הטובה ביותר: צלמו את כל הצלחת בתאורה טובה.",processingTitle:"Beyond מכין את התמונה",processingText:"בודק איכות, משפר את התמונה ומתאים אותה לסגנון התפריט."},
  ar:{label:"صورة الطبق",intro:"صوّر الطبق الحقيقي. سيحسّن Beyond الصورة ويطابقها مع أسلوب قائمتك.",take:"التقط صورة",choose:"اختر من الهاتف",replace:"استبدال",remove:"إزالة",signIn:"سجّل الدخول لإضافة صورة",authRequired:"سجّل الدخول إلى Beyond لرفع صور القائمة وحفظها.",uploading:"نجعل الصورة جاهزة للقائمة…",drop:"أفلت صورة الطبق هنا",empty:"أضف صورة حقيقية لهذا الطبق",error:"فشل رفع الصورة",standard:"فحص صور Beyond",original:"الأصل",enhanced:"محسّنة",theme:"أسلوب القائمة",recommended:"موصى بها",currentMenu:"مطابقة لـ",natural:"يبقى الطبق حقيقياً — Beyond يحسّن طريقة عرضه فقط.",themeSafe:"هذه النسخة تتبع أسلوب صور قائمتك بدون تغيير الطبق.",retune:"مطابقة أسلوب القائمة",retuning:"جارٍ المطابقة…",themeOutdated:"تغيّر أسلوب القائمة. حدّث الصورة لتطابقه.",excellent:"ممتاز",good:"تبدو جيدة",needs_improvement:"يمكن تحسينها",low_quality:"جرّب صورة أخرى",framing:"اختر نقطة التركيز",framingHint:"حرّك المؤشر إلى أهم جزء من الطبق.",adjustFraming:"ضبط التركيز",doneFraming:"تم",centerFraming:"توسيط",analyzedOnce:"صورة ذكية",cached:"جاهزة لإعادة الاستخدام عبر تصاميم القائمة",reanalyze:"تحديث",reanalyzing:"جارٍ التحديث…",reanalyzeHint:"حدّث فقط إذا تغيّرت الصورة الأصلية.",step1:"1 · أضف",step2:"2 · Beyond يحسّن",step3:"3 · اختر المظهر",tip:"لأفضل نتيجة: صوّر الطبق كاملاً بإضاءة جيدة.",processingTitle:"Beyond يجهّز صورتك",processingText:"يفحص الجودة ويحسّن الصورة ويطابقها مع أسلوب القائمة."},
};

const NOTE_COPY = {
  en:{low_resolution:"A larger photo will look sharper.",medium_resolution:"A larger photo would look even sharper.",too_dark:"The photo is too dark.",slightly_dark:"The photo is slightly dark.",too_bright:"Highlights are too bright.",slightly_bright:"The photo is slightly bright.",low_contrast:"The photo needs more separation.",soft_contrast:"Contrast is a little soft.",soft_focus:"The photo may be out of focus.",slightly_soft:"The photo is slightly soft."},
  he:{low_resolution:"תמונה גדולה יותר תיראה חדה יותר.",medium_resolution:"תמונה גדולה יותר תיראה חדה עוד יותר.",too_dark:"התמונה כהה מדי.",slightly_dark:"התמונה מעט כהה.",too_bright:"האזורים הבהירים חזקים מדי.",slightly_bright:"התמונה מעט בהירה מדי.",low_contrast:"התמונה זקוקה ליותר הפרדה.",soft_contrast:"הניגודיות מעט רכה.",soft_focus:"ייתכן שהתמונה אינה בפוקוס.",slightly_soft:"התמונה מעט רכה."},
  ar:{low_resolution:"صورة أكبر ستبدو أكثر حدة.",medium_resolution:"صورة أكبر ستبدو أكثر حدة.",too_dark:"الصورة داكنة جداً.",slightly_dark:"الصورة داكنة قليلاً.",too_bright:"الإضاءة الساطعة قوية جداً.",slightly_bright:"الصورة ساطعة قليلاً.",low_contrast:"الصورة تحتاج إلى فصل أوضح.",soft_contrast:"التباين ناعم قليلاً.",soft_focus:"قد تكون الصورة خارج نطاق التركيز.",slightly_soft:"الصورة ناعمة قليلاً."},
};

const clampFocus = value => { const n=Number(value); return Number.isFinite(n)?Math.min(100,Math.max(0,n)):50; };
const roundedFocus = value => Math.round(clampFocus(value)*10)/10;

function finishPatch(finish){return {image_finish_profile:finish?.profile||"dish-safe-pro-v1",image_finish_source:finish?.source||"local-vision",image_finish_safety:finish?.safety||"dish-integrity-locked",image_finish_confidence:Number.isFinite(Number(finish?.confidence))?Number(finish.confidence):null,image_finish_model:finish?.model||"",image_finish_recipe:finish?.recipe||null};}
function assetPatch(result){const asset=result?.asset;if(!asset)return{};return{photo_asset_id:asset.id,image_hash:result.imageHash||asset.image_hash||"",image_analysis_profile:result.analysisProfile||asset.analysis_profile||"",image_original_url:asset.original_url||result.original?.url||"",image_original_path:asset.original_path||result.original?.path||"",image_processed_url:asset.processed_url||result.processed?.url||asset.original_url||"",image_processed_path:asset.processed_path||result.processed?.path||asset.original_path||"",image_quality_score:Number.isFinite(Number(asset.quality_score))?Number(asset.quality_score):result.analysis?.score??null,image_quality_level:asset.quality_level||result.analysis?.level||"",image_quality_notes:Array.isArray(asset.quality_notes)?asset.quality_notes:(result.analysis?.notes||[]),image_focus_x:Number.isFinite(Number(asset.focus_x))?Number(asset.focus_x):50,image_focus_y:Number.isFinite(Number(asset.focus_y))?Number(asset.focus_y):50,image_processing_profile:asset.analysis?.processingProfile||result.profile||"natural-auto-v2",image_processed_at:asset.analyzed_at||result.processedAt||null};}

export default function MenuStudioItemPhotoField({item,onChange,siteId,slug,studioLanguage="en"}){
  const copy=COPY[studioLanguage]||COPY.en; const noteCopy=NOTE_COPY[studioLanguage]||NOTE_COPY.en;
  const libraryRef=useRef(null), cameraRef=useRef(null), focusDraggingRef=useRef(false);
  const [uploading,setUploading]=useState(false),[retuning,setRetuning]=useState(false),[reanalyzing,setReanalyzing]=useState(false),[dragging,setDragging]=useState(false),[error,setError]=useState(""),[authUser,setAuthUser]=useState(undefined),[authOpen,setAuthOpen]=useState(false),[focusMode,setFocusMode]=useState(false),[focusPoint,setFocusPoint]=useState({x:50,y:50});
  useEffect(()=>{let active=true;supabase.auth.getSession().then(({data})=>{if(active)setAuthUser(data?.session?.user||null)}).catch(()=>{if(active)setAuthUser(null)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>{if(active)setAuthUser(s?.user||null)});return()=>{active=false;data?.subscription?.unsubscribe?.();};},[]);
  useEffect(()=>{if(authUser)setError(current=>current===copy.authRequired?"":current);},[authUser,copy.authRequired]);
  const currentDesign=getCurrentDraftDesign({siteId,slug})||{}, currentThemeProfile=resolveMenuPhotoProfile(currentDesign), currentThemeLabel=menuPhotoProfileLabel(currentThemeProfile,studioLanguage), currentThemeDescription=menuPhotoProfileDescription(currentThemeProfile,studioLanguage);
  const imageUrl=String(item?.image_url||""),originalUrl=String(item?.image_original_url||""),processedUrl=String(item?.image_processed_url||""),themeUrl=String(item?.image_theme_url||""),originalPath=String(item?.image_original_path||""),processedPath=String(item?.image_processed_path||""),themePath=String(item?.image_theme_path||""),storedThemeProfile=String(item?.image_theme_profile||""),photoAssetId=String(item?.photo_asset_id||"");
  const qualityScore=Number.isFinite(Number(item?.image_quality_score))?Number(item.image_quality_score):null, qualityLevel=String(item?.image_quality_level||""), qualityNotes=Array.isArray(item?.image_quality_notes)?item.image_quality_notes:[], savedFocusX=clampFocus(item?.image_focus_x),savedFocusY=clampFocus(item?.image_focus_y),activeVariant=item?.image_variant==="original"?"original":item?.image_variant==="theme"?"theme":"enhanced",hasComparison=Boolean((originalUrl&&processedUrl)||photoAssetId),themeIsCurrent=Boolean(themeUrl&&storedThemeProfile===currentThemeProfile.id),finishIsCurrent=item?.image_finish_profile==="dish-safe-pro-v1"&&item?.image_finish_safety==="dish-integrity-locked",themeNeedsUpdate=Boolean((originalUrl||processedUrl||photoAssetId)&&(!themeIsCurrent||!finishIsCurrent||!photoAssetId)),busy=uploading||retuning||reanalyzing,displayedFocus=focusMode?focusPoint:{x:savedFocusX,y:savedFocusY};
  useEffect(()=>{if(!focusMode)setFocusPoint({x:savedFocusX,y:savedFocusY});},[savedFocusX,savedFocusY,focusMode]);
  function handlePhotoError(err){if(err?.code===MENU_PHOTO_AUTH_REQUIRED){setAuthUser(null);setError(copy.authRequired);setAuthOpen(true);return;}setError(err?.message||copy.error);}
  function requestSource(ref){setError("");if(!authUser){setAuthOpen(true);return;}ref.current?.click();}
  async function handleFile(file){if(!file||busy)return;setError("");setUploading(true);try{const uploaded=await uploadMenuItemImage({file,siteId,slug,itemId:item?.id,themeProfile:currentThemeProfile});const selected=uploaded.theme||uploaded.processed;const smartFocus=uploaded.focus||{x:50,y:50};const nextFocus={x:roundedFocus(smartFocus.x),y:roundedFocus(smartFocus.y)};onChange?.({...assetPatch(uploaded),...finishPatch(uploaded.finish),image_url:selected.url,image_path:selected.path,image_original_url:uploaded.original?.url||"",image_original_path:uploaded.original?.path||"",image_processed_url:uploaded.processed?.url||"",image_processed_path:uploaded.processed?.path||"",image_theme_url:uploaded.theme?.url||"",image_theme_path:uploaded.theme?.path||"",image_theme_profile:uploaded.themeProfile||"",image_theme_processed_at:uploaded.theme?uploaded.processedAt:null,image_width:selected.width,image_height:selected.height,image_focus_x:nextFocus.x,image_focus_y:nextFocus.y,image_variant:uploaded.theme?"theme":"enhanced",image_status:"ready"});setFocusPoint(nextFocus);}catch(err){handlePhotoError(err);}finally{setUploading(false);if(libraryRef.current)libraryRef.current.value="";if(cameraRef.current)cameraRef.current.value="";}}
  async function retuneCurrentTheme(){if(busy||!(originalUrl||processedUrl||photoAssetId))return;setError("");setRetuning(true);try{const tuned=await retuneMenuItemImage({sourceUrl:originalUrl||processedUrl,sourcePath:originalPath||processedPath,siteId,slug,itemId:item?.id,themeProfile:currentThemeProfile,photoAssetId});onChange?.({...assetPatch(tuned),...finishPatch(tuned.finish),image_url:tuned.theme.url,image_path:tuned.theme.path,image_theme_url:tuned.theme.url,image_theme_path:tuned.theme.path,image_theme_profile:tuned.themeProfile,image_theme_processed_at:tuned.processedAt,image_width:tuned.theme.width,image_height:tuned.theme.height,image_variant:"theme",image_status:"ready"});}catch(err){handlePhotoError(err);}finally{setRetuning(false);}}
  async function reanalyzePhoto(){if(busy||!(originalUrl||processedUrl||photoAssetId))return;setError("");setReanalyzing(true);try{const analyzed=await reanalyzeMenuItemImage({sourceUrl:originalUrl||processedUrl,sourcePath:originalPath||processedPath,siteId,slug,itemId:item?.id,themeProfile:currentThemeProfile,photoAssetId});const selected=analyzed.theme||analyzed.processed;onChange?.({...assetPatch(analyzed),...finishPatch(analyzed.finish),image_url:selected?.url||imageUrl,image_path:selected?.path||item?.image_path||"",image_theme_url:analyzed.theme?.url||"",image_theme_path:analyzed.theme?.path||"",image_theme_profile:analyzed.themeProfile||"",image_theme_processed_at:analyzed.theme?analyzed.processedAt:null,image_width:selected?.width||item?.image_width||null,image_height:selected?.height||item?.image_height||null,image_variant:analyzed.theme?"theme":"enhanced",image_status:"ready"});}catch(err){handlePhotoError(err);}finally{setReanalyzing(false);}}
  function handleDrop(event){event.preventDefault();setDragging(false);if(focusMode)return;if(!authUser){setAuthOpen(true);return;}const file=event.dataTransfer?.files?.[0];if(file)handleFile(file);}
  function chooseVariant(v){if(v==="original"&&originalUrl)return onChange?.({image_url:originalUrl,image_path:originalPath,image_variant:"original"});if(v==="theme"&&themeUrl)return onChange?.({image_url:themeUrl,image_path:themePath,image_variant:"theme"});if(processedUrl)onChange?.({image_url:processedUrl,image_path:processedPath,image_variant:"enhanced"});}
  function removePhoto(){setError("");setFocusMode(false);setFocusPoint({x:50,y:50});onChange?.({image_url:"",image_path:"",image_original_url:"",image_original_path:"",image_processed_url:"",image_processed_path:"",image_theme_url:"",image_theme_path:"",image_theme_profile:"",image_theme_processed_at:null,photo_asset_id:"",image_hash:"",image_analysis_profile:"",image_width:null,image_height:null,image_focus_x:50,image_focus_y:50,image_variant:"",image_status:"none",image_quality_score:null,image_quality_level:"",image_quality_notes:[],image_processing_profile:"",image_processed_at:null,image_finish_profile:"",image_finish_source:"",image_finish_safety:"",image_finish_confidence:null,image_finish_model:"",image_finish_recipe:null});}
  function pointFromPointer(e){const b=e.currentTarget.getBoundingClientRect();if(!b.width||!b.height)return focusPoint;return{x:roundedFocus(((e.clientX-b.left)/b.width)*100),y:roundedFocus(((e.clientY-b.top)/b.height)*100)};}
  function commitFocus(p=focusPoint){const n={x:roundedFocus(p.x),y:roundedFocus(p.y)};setFocusPoint(n);onChange?.({image_focus_x:n.x,image_focus_y:n.y});}
  function pointerDown(e){e.preventDefault();focusDraggingRef.current=true;e.currentTarget.setPointerCapture?.(e.pointerId);setFocusPoint(pointFromPointer(e));} function pointerMove(e){if(focusDraggingRef.current)setFocusPoint(pointFromPointer(e));} function pointerUp(e){if(!focusDraggingRef.current)return;focusDraggingRef.current=false;const n=pointFromPointer(e);commitFocus(n);e.currentTarget.releasePointerCapture?.(e.pointerId);}
  return <section className="studio-v3-item-photo-field">
    <div className="studio-v3-photo-friendly-head"><div><span className="studio-v3-photo-eyebrow">BEYOND PHOTO</span><strong>{copy.label}</strong><p>{copy.intro}</p></div>{imageUrl?<span className="studio-v3-photo-ready">✓ Ready</span>:null}</div>
    {!imageUrl?<div className="studio-v3-photo-steps" aria-hidden="true"><span>{copy.step1}</span><i>→</i><span>{copy.step2}</span><i>→</i><span>{copy.step3}</span></div>:null}
    <div className={`studio-v3-item-photo-dropzone ${imageUrl?"has-image":"empty"} ${dragging?"is-dragging":""} ${busy?"is-uploading":""} ${focusMode?"is-framing":""}`} onDragEnter={e=>{if(!focusMode){e.preventDefault();setDragging(true)}}} onDragOver={e=>e.preventDefault()} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget))setDragging(false)}} onDrop={handleDrop}>
      {imageUrl?<img src={imageUrl} alt="" style={{objectPosition:`${displayedFocus.x}% ${displayedFocus.y}%`}}/>:<div className="studio-v3-item-photo-empty"><span className="studio-v3-item-photo-icon" aria-hidden="true"><i/><i/></span><strong>{dragging?copy.drop:copy.empty}</strong><small>{copy.tip}</small></div>}
      {focusMode&&imageUrl?<div className="studio-v3-item-photo-focus-layer" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={()=>{focusDraggingRef.current=false}}><span className="studio-v3-item-photo-focus-target" style={{left:`${focusPoint.x}%`,top:`${focusPoint.y}%`}}><i/><i/></span></div>:null}
      {uploading?<div className="studio-v3-photo-processing"><span className="studio-v3-photo-spinner"/><strong>{copy.processingTitle}</strong><small>{copy.processingText}</small></div>:null}
      <div className="studio-v3-item-photo-overlay">{focusMode?<><button type="button" className="primary" onClick={()=>{commitFocus();setFocusMode(false)}}>{copy.doneFraming}</button><button type="button" className="secondary" onClick={()=>commitFocus({x:50,y:50})}>{copy.centerFraming}</button></>:imageUrl?<><button type="button" className="primary" disabled={busy} onClick={()=>requestSource(libraryRef)}>{copy.replace}</button><button type="button" className="secondary" disabled={busy} onClick={removePhoto}>{copy.remove}</button></>:null}</div>
    </div>
    {!imageUrl?<div className="studio-v3-photo-source-actions"><button type="button" className="camera" disabled={busy} onClick={()=>requestSource(cameraRef)}><span className="studio-v3-photo-action-icon">⌁</span><strong>{authUser===null?copy.signIn:copy.take}</strong><small>Camera</small></button><button type="button" disabled={busy} onClick={()=>requestSource(libraryRef)}><span className="studio-v3-photo-action-icon">▧</span><strong>{authUser===null?copy.signIn:copy.choose}</strong><small>Photo library</small></button></div>:null}
    {imageUrl?<div className={`studio-v3-item-photo-framing-row ${focusMode?"active":""}`}><div><strong>{copy.framing}</strong><span>{copy.framingHint}</span></div>{!focusMode?<button type="button" disabled={busy} onClick={()=>{setFocusPoint({x:savedFocusX,y:savedFocusY});setFocusMode(true)}}>{copy.adjustFraming}</button>:<span className="studio-v3-item-photo-focus-coordinates">{Math.round(focusPoint.x)} · {Math.round(focusPoint.y)}</span>}</div>:null}
    {hasComparison?<div className="studio-v3-item-photo-tuning"><div className="studio-v3-item-photo-standard-head"><div><span>{copy.standard}</span><strong>{qualityLevel?copy[qualityLevel]||qualityLevel:copy.good}</strong></div>{qualityScore!==null?<b className={`quality-${qualityLevel||"good"}`}>{qualityScore}/100</b>:null}</div><div className="studio-v3-item-photo-theme-profile"><div><span>{copy.currentMenu}</span><strong>{currentThemeLabel}</strong><small>{currentThemeDescription}</small></div>{themeIsCurrent&&finishIsCurrent&&photoAssetId?<span className="is-matched">✓ {copy.theme}</span>:null}</div>
      <MenuPhotoReviewCompare originalUrl={originalUrl} finishedUrl={themeUrl||processedUrl} finishedKind={themeUrl?"theme":"enhanced"} activeVariant={activeVariant} focusX={savedFocusX} focusY={savedFocusY} finishSource={item?.image_finish_source||""} finishSafety={item?.image_finish_safety||""} language={studioLanguage} onSelect={chooseVariant}/>
      <div className="studio-v3-item-photo-variants"><button type="button" className={activeVariant==="original"?"active":""} onClick={()=>chooseVariant("original")}>{copy.original}</button><button type="button" className={activeVariant==="enhanced"?"active":""} onClick={()=>chooseVariant("enhanced")}>{copy.enhanced}</button><button type="button" className={`${activeVariant==="theme"?"active":""} theme-variant`} disabled={!themeUrl} onClick={()=>chooseVariant("theme")}><span>{copy.theme}</span>{themeIsCurrent&&finishIsCurrent&&photoAssetId?<small>{copy.recommended}</small>:null}</button></div>
      {themeNeedsUpdate?<div className="studio-v3-item-photo-retune"><span>{copy.themeOutdated}</span><button type="button" disabled={busy} onClick={retuneCurrentTheme}>{retuning?copy.retuning:copy.retune}</button></div>:null}<p className="studio-v3-item-photo-natural-note">{activeVariant==="theme"?copy.themeSafe:copy.natural}</p>{qualityNotes.length?<div className="studio-v3-item-photo-notes">{qualityNotes.slice(0,3).map(code=><span key={code}>{noteCopy[code]||code}</span>)}</div>:null}{photoAssetId?<button type="button" className="studio-v3-photo-refresh" disabled={busy} onClick={reanalyzePhoto}>{reanalyzing?copy.reanalyzing:copy.reanalyze}</button>:null}</div>:null}
    <input ref={cameraRef} className="studio-v3-item-photo-native-input" type="file" accept="image/*" capture="environment" onChange={e=>handleFile(e.target.files?.[0])}/><input ref={libraryRef} className="studio-v3-item-photo-native-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>handleFile(e.target.files?.[0])}/>{error?<div className="studio-v3-item-photo-error" role="alert">{error}</div>:null}<AuthModal open={authOpen} onClose={()=>setAuthOpen(false)} initialMode="login"/>
  </section>;
}
