export const PHASE3_MENU_DESIGNS = Object.freeze([
  {
    id:"trattoria-ledger",
    name:"Trattoria Ledger",
    category:"Italian",
    layout:"Ledger",
    description:"Warm Italian menu-book styling with disciplined rows, serif headings and aligned prices.",
    tags:["italian","trattoria","ledger","classic","wine","warm"],
    swatches:["#f7efe3","#a33f2e","#2c211c"],
    design:{template:"ledger",styleVariant:"standard",theme:{background:"#f7efe3",surface:"#fff9ef",card:"#fffdf8",text:"#2c211c",muted:"#7d6f65",accent:"#a33f2e",accentSecondary:"#d7b188",line:"#decfc1",categoryBackground:"#a33f2e",categoryText:"#ffffff"},typography:{headingFont:"Merriweather",bodyFont:"DM Sans",numberFont:"Merriweather",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:48,sectionSize:34,itemNameSize:16,descriptionSize:11,priceSize:16},layout:{density:"comfortable",navigationStyle:"underline",pricePosition:"inline",cardRadius:0,sectionGap:30,itemGap:10,cardPadding:12},brand:{heroMediaMode:"watermark"}},
  },
  {
    id:"tokyo-ink",
    name:"Tokyo Ink",
    category:"Japanese",
    layout:"Editorial",
    description:"Ink-black typography, red accents and disciplined whitespace for sushi and omakase menus.",
    tags:["japanese","sushi","omakase","editorial","minimal","ink"],
    swatches:["#f1f0eb","#b5362d","#191a18"],
    design:{template:"editorial",styleVariant:"standard",theme:{background:"#f1f0eb",surface:"#f8f7f2",card:"#f8f7f2",text:"#191a18",muted:"#74756f",accent:"#b5362d",accentSecondary:"#d8d3c8",line:"#d4d0c6",categoryBackground:"#191a18",categoryText:"#ffffff"},typography:{headingFont:"Noto Sans Hebrew",bodyFont:"Inter",numberFont:"Inter",headingWeight:500,bodyWeight:400,itemWeight:600,heroSize:46,sectionSize:32,itemNameSize:15,descriptionSize:11,priceSize:15},layout:{density:"spacious",navigationStyle:"underline",pricePosition:"inline",cardRadius:0,sectionGap:40,itemGap:15,cardPadding:12},brand:{heroMediaMode:"none"}},
  },
  {
    id:"garden-split",
    name:"Garden Split",
    category:"Farm to Table",
    layout:"Split",
    description:"Botanical tones and alternating image panels for seasonal, farm-led restaurants.",
    tags:["garden","farm","organic","split","seasonal","healthy"],
    swatches:["#eef2e8","#4b704a","#283228"],
    design:{template:"split",styleVariant:"standard",theme:{background:"#eef2e8",surface:"#f8faf4",card:"#ffffff",text:"#283228",muted:"#748070",accent:"#4b704a",accentSecondary:"#cdd9b9",line:"#d7ded0",categoryBackground:"#4b704a",categoryText:"#ffffff"},typography:{headingFont:"Lora",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:56,sectionSize:38,itemNameSize:18,descriptionSize:12,priceSize:16},layout:{density:"spacious",navigationStyle:"minimal",itemImagePosition:"left",itemImageRatio:"4:3",pricePosition:"below",cardRadius:24,sectionGap:38,itemGap:26,cardPadding:22},brand:{heroMediaMode:"image"}},
  },
  {
    id:"bakery-tiles",
    name:"Bakery Tiles",
    category:"Bakery & Café",
    layout:"Tiles",
    description:"Soft pastry-shop tiles with rounded imagery, warm cream surfaces and compact browsing.",
    tags:["bakery","cafe","pastry","tiles","brunch","friendly"],
    swatches:["#fff3e7","#b86b4b","#442f27"],
    design:{template:"tiles",styleVariant:"standard",theme:{background:"#fff3e7",surface:"#fff8f1",card:"#ffffff",text:"#442f27",muted:"#89766d",accent:"#b86b4b",accentSecondary:"#e6c0a6",line:"#ebd9cc",categoryBackground:"#b86b4b",categoryText:"#ffffff"},typography:{headingFont:"DM Sans",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:44,sectionSize:32,itemNameSize:16,descriptionSize:12,priceSize:16},layout:{density:"comfortable",navigationStyle:"pills",itemImagePosition:"top",itemImageRatio:"1:1",pricePosition:"inline",cardRadius:28,sectionGap:28,itemGap:14,cardPadding:15},brand:{heroMediaMode:"watermark"}},
  },
  {
    id:"neon-bottom-tabs",
    name:"Neon Bottom Tabs",
    category:"Nightlife",
    layout:"Bottom Tabs",
    description:"Electric mobile navigation with a persistent bottom dock for late-night bars and clubs.",
    tags:["nightlife","neon","bottom tabs","mobile","bar","club"],
    swatches:["#10111a","#7c5cff","#f3f0ff"],
    design:{template:"tiles",styleVariant:"standard",theme:{background:"#10111a",surface:"#151724",card:"#1b1e2d",text:"#f3f0ff",muted:"#9d9aae",accent:"#7c5cff",accentSecondary:"#34304c",line:"#2b2e40",categoryBackground:"#7c5cff",categoryText:"#ffffff"},typography:{headingFont:"Poppins",bodyFont:"DM Sans",numberFont:"Poppins",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:50,sectionSize:34,itemNameSize:17,descriptionSize:11,priceSize:17},layout:{presentation:"bottom-tabs",density:"comfortable",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"1:1",pricePosition:"inline",cardRadius:22,sectionGap:28,itemGap:14,cardPadding:15},brand:{heroMediaMode:"image"}},
  },
  {
    id:"desert-covers",
    name:"Desert Covers",
    category:"Middle Eastern",
    layout:"Category Covers",
    description:"Terracotta category panels and warm sand tones for mezze, grill and Levantine menus.",
    tags:["middle eastern","mezze","grill","covers","terracotta","categories"],
    swatches:["#f4e9da","#a94f37","#382a23"],
    design:{template:"classic",styleVariant:"standard",theme:{background:"#f4e9da",surface:"#fbf4ea",card:"#ffffff",text:"#382a23",muted:"#807064",accent:"#a94f37",accentSecondary:"#d7ad80",line:"#decdbb",categoryBackground:"#704638",categoryText:"#ffffff"},typography:{headingFont:"Lora",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:56,sectionSize:36,itemNameSize:16,descriptionSize:12,priceSize:16},layout:{presentation:"category-covers",density:"comfortable",navigationStyle:"minimal",pricePosition:"inline",cardRadius:20,sectionGap:32,itemGap:14,cardPadding:15},brand:{heroMediaMode:"watermark"}},
  },
  {
    id:"tapas-magazine",
    name:"Tapas Magazine",
    category:"Spanish",
    layout:"Magazine",
    description:"Editorial photo rhythm and lively red accents for tapas bars and social dining.",
    tags:["spanish","tapas","magazine","editorial","photos","social"],
    swatches:["#f5eee4","#bb3d2e","#24201d"],
    design:{template:"visual",styleVariant:"standard",theme:{background:"#f5eee4",surface:"#fbf7f0",card:"#ffffff",text:"#24201d",muted:"#786f68",accent:"#bb3d2e",accentSecondary:"#dfb38d",line:"#ddd2c7",categoryBackground:"#24201d",categoryText:"#ffffff"},typography:{headingFont:"Playfair Display",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:62,sectionSize:40,itemNameSize:18,descriptionSize:12,priceSize:16},layout:{presentation:"magazine",density:"spacious",navigationStyle:"underline",itemImagePosition:"top",itemImageRatio:"4:3",pricePosition:"inline",cardRadius:2,sectionGap:40,itemGap:22,cardPadding:16},brand:{heroMediaMode:"image"}},
  },
  {
    id:"steakhouse-ledger",
    name:"Steakhouse Ledger",
    category:"Steakhouse",
    layout:"Ledger",
    description:"Dark masculine ledger with restrained bronze accents and highly legible pricing.",
    tags:["steakhouse","grill","ledger","dark","premium","meat"],
    swatches:["#17191a","#b78252","#f1ece5"],
    design:{template:"ledger",styleVariant:"standard",theme:{background:"#17191a",surface:"#1d2021",card:"#1d2021",text:"#f1ece5",muted:"#aaa29a",accent:"#b78252",accentSecondary:"#4c4036",line:"#343739",categoryBackground:"#b78252",categoryText:"#17191a"},typography:{headingFont:"Merriweather",bodyFont:"DM Sans",numberFont:"Merriweather",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:50,sectionSize:34,itemNameSize:16,descriptionSize:11,priceSize:16},layout:{density:"comfortable",navigationStyle:"minimal",pricePosition:"inline",cardRadius:0,sectionGap:28,itemGap:10,cardPadding:12},brand:{heroMediaMode:"none"}},
  },
  {
    id:"brunch-photo-story",
    name:"Brunch Photo Story",
    category:"Brunch",
    layout:"Photo Story",
    description:"Immersive full-width breakfast imagery with oversized captions and simple prices.",
    tags:["brunch","breakfast","photo story","visual","cafe","immersive"],
    swatches:["#efe8de","#d77a4a","#2e2925"],
    design:{template:"visual",styleVariant:"standard",theme:{background:"#efe8de",surface:"#f7f1e8",card:"#181715",text:"#fffaf3",muted:"#d0c6bb",accent:"#d77a4a",accentSecondary:"#7d5b49",line:"#4a423c",categoryBackground:"#fffaf3",categoryText:"#2e2925"},typography:{headingFont:"Playfair Display",bodyFont:"Inter",numberFont:"Inter",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:60,sectionSize:38,itemNameSize:21,descriptionSize:13,priceSize:18},layout:{presentation:"photo-story",density:"spacious",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"16:9",pricePosition:"inline",cardRadius:0,sectionGap:24,itemGap:18,cardPadding:20},brand:{heroMediaMode:"image"}},
  },
  {
    id:"rose-cocktail-cards",
    name:"Rose Cocktail Cards",
    category:"Rooftop Bar",
    layout:"Cocktail Cards",
    description:"Soft rose-on-charcoal drink cards for rooftop bars, lounges and modern cocktail lists.",
    tags:["cocktail","rooftop","lounge","rose","cards","drinks"],
    swatches:["#19171b","#d68f9d","#f7eff2"],
    design:{template:"visual",styleVariant:"standard",theme:{background:"#19171b",surface:"#211e23",card:"#272229",text:"#f7eff2",muted:"#b3a8ae",accent:"#d68f9d",accentSecondary:"#4b3940",line:"#3a3238",categoryBackground:"#d68f9d",categoryText:"#19171b"},typography:{headingFont:"Playfair Display",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:600,bodyWeight:400,itemWeight:600,heroSize:58,sectionSize:36,itemNameSize:19,descriptionSize:12,priceSize:16},layout:{presentation:"cocktail-cards",density:"spacious",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"3:2",pricePosition:"inline",cardRadius:26,sectionGap:34,itemGap:22,cardPadding:18},brand:{heroMediaMode:"image"}},
  },
  {
    id:"blue-category-launcher",
    name:"Blue Category Launcher",
    category:"Modern Casual",
    layout:"Launcher",
    description:"A bold blue category-first entrance that feels like opening a polished mobile app.",
    tags:["launcher","blue","categories","mobile","app","modern"],
    swatches:["#f7f5f2","#4974e5","#182238"],
    design:{template:"classic",styleVariant:"standard",theme:{background:"#f7f5f2",surface:"#ffffff",card:"#ffffff",text:"#182238",muted:"#7b8494",accent:"#4974e5",accentSecondary:"#dbe4ff",line:"#e0e3e8",categoryBackground:"#182238",categoryText:"#ffffff"},typography:{headingFont:"DM Sans",bodyFont:"Inter",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:52,sectionSize:34,itemNameSize:16,descriptionSize:11,priceSize:16},layout:{presentation:"launcher",density:"comfortable",navigationStyle:"minimal",pricePosition:"inline",cardRadius:0,sectionGap:34,itemGap:14,cardPadding:14},brand:{heroMediaMode:"none"}},
  },
]);
