export const PHASE4_MENU_DESIGNS = Object.freeze([
  {
    id:"levant-table",
    name:"Levant Table",
    category:"Middle Eastern",
    layout:"Category Covers",
    description:"Warm stone tones and bold category panels for mezze, grill and sharing menus.",
    tags:["levant","middle eastern","mezze","covers","sharing","mobile"],
    swatches:["#f3ede2","#8d5738","#2b241f"],
    design:{template:"classic",styleVariant:"standard",theme:{background:"#f3ede2",surface:"#fbf7ef",card:"#ffffff",text:"#2b241f",muted:"#7d746d",accent:"#c47c50",accentSecondary:"#dac2a2",line:"#dfd3c4",categoryBackground:"#8d5738",categoryText:"#ffffff"},typography:{headingFont:"Lora",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:54,sectionSize:36,itemNameSize:17,descriptionSize:12,priceSize:16},layout:{presentation:"category-covers",density:"comfortable",navigationStyle:"minimal",pricePosition:"inline",cardRadius:20,sectionGap:32,itemGap:14,cardPadding:16},brand:{heroMediaMode:"watermark"}},
  },
  {
    id:"mezze-mosaic",
    name:"Mezze Mosaic",
    category:"Shared Plates",
    layout:"Tiles",
    description:"A colorful tile system designed for many small plates and quick visual scanning.",
    tags:["mezze","sharing","tiles","photos","casual","colorful"],
    swatches:["#fff4e6","#db7549","#274b46"],
    design:{template:"tiles",styleVariant:"standard",theme:{background:"#fff4e6",surface:"#fff9f1",card:"#ffffff",text:"#263a37",muted:"#77827d",accent:"#db7549",accentSecondary:"#f2c67f",line:"#ead8c5",categoryBackground:"#274b46",categoryText:"#ffffff"},typography:{headingFont:"Poppins",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:48,sectionSize:34,itemNameSize:17,descriptionSize:12,priceSize:16},layout:{density:"comfortable",navigationStyle:"pills",itemImagePosition:"top",itemImageRatio:"1:1",pricePosition:"inline",cardRadius:24,sectionGap:28,itemGap:14,cardPadding:15},brand:{heroMediaMode:"image"}},
  },
  {
    id:"nordic-paper",
    name:"Nordic Paper",
    category:"Modern Dining",
    layout:"Minimal Grid",
    description:"Quiet Scandinavian spacing, soft gray paper and disciplined two-column typography.",
    tags:["nordic","minimal","grid","clean","text","fine dining"],
    swatches:["#f4f4f1","#4a5a63","#171a1c"],
    design:{template:"classic",styleVariant:"standard",theme:{background:"#f4f4f1",surface:"#fbfbf8",card:"#ffffff",text:"#171a1c",muted:"#7c8284",accent:"#4a5a63",accentSecondary:"#d8dddc",line:"#daddd9",categoryBackground:"#171a1c",categoryText:"#ffffff"},typography:{headingFont:"Montserrat",bodyFont:"Inter",numberFont:"Inter",headingWeight:600,bodyWeight:400,itemWeight:600,heroSize:52,sectionSize:35,itemNameSize:16,descriptionSize:11,priceSize:15},layout:{presentation:"minimal-grid",density:"spacious",navigationStyle:"underline",pricePosition:"inline",cardRadius:0,sectionGap:40,itemGap:16,cardPadding:12},brand:{heroMediaMode:"none"}},
  },
  {
    id:"seoul-night",
    name:"Seoul Night",
    category:"Korean Bar",
    layout:"Cocktail Cards",
    description:"Electric dark cards with neon accents for late-night Korean dining and drinks.",
    tags:["korean","night","dark","cocktails","bar","cards","photos"],
    swatches:["#101116","#e44869","#f5f2ed"],
    design:{template:"visual",styleVariant:"standard",theme:{background:"#101116",surface:"#161821",card:"#1b1e29",text:"#f5f2ed",muted:"#a0a4b0",accent:"#e44869",accentSecondary:"#493241",line:"#303342",categoryBackground:"#e44869",categoryText:"#ffffff"},typography:{headingFont:"Poppins",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:58,sectionSize:36,itemNameSize:19,descriptionSize:12,priceSize:17},layout:{presentation:"cocktail-cards",density:"spacious",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"3:2",pricePosition:"inline",cardRadius:22,sectionGap:34,itemGap:20,cardPadding:18},brand:{heroMediaMode:"image"}},
  },
  {
    id:"paris-patisserie",
    name:"Paris Patisserie",
    category:"Dessert & Pastry",
    layout:"Gallery",
    description:"Elegant pastry photography, delicate serif type and a polished gallery rhythm.",
    tags:["pastry","dessert","bakery","gallery","photos","french","elegant"],
    swatches:["#fbf4f4","#b46f79","#35282b"],
    design:{template:"gallery",styleVariant:"standard",theme:{background:"#fbf4f4",surface:"#fffafa",card:"#ffffff",text:"#35282b",muted:"#8a777b",accent:"#b46f79",accentSecondary:"#ead4d7",line:"#eadfe1",categoryBackground:"#35282b",categoryText:"#ffffff"},typography:{headingFont:"Playfair Display",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:600,bodyWeight:400,itemWeight:600,heroSize:58,sectionSize:38,itemNameSize:18,descriptionSize:12,priceSize:16},layout:{density:"spacious",navigationStyle:"underline",itemImagePosition:"top",itemImageRatio:"1:1",pricePosition:"below",cardRadius:18,sectionGap:42,itemGap:22,cardPadding:16},brand:{heroMediaMode:"image"}},
  },
  {
    id:"smokehouse-story",
    name:"Smokehouse Story",
    category:"BBQ & Grill",
    layout:"Photo Story",
    description:"Full-bleed smoky food scenes with oversized names and bold prices layered on photography.",
    tags:["bbq","grill","smokehouse","photo story","dark","photos","immersive"],
    swatches:["#161310","#b65d32","#f3eadf"],
    design:{template:"visual",styleVariant:"standard",theme:{background:"#161310",surface:"#1c1814",card:"#111111",text:"#f3eadf",muted:"#b1a69a",accent:"#d07642",accentSecondary:"#4c382b",line:"#3d332c",categoryBackground:"#f3eadf",categoryText:"#161310"},typography:{headingFont:"Merriweather",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:62,sectionSize:38,itemNameSize:22,descriptionSize:13,priceSize:18},layout:{presentation:"photo-story",density:"spacious",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"16:9",pricePosition:"inline",cardRadius:0,sectionGap:24,itemGap:18,cardPadding:20},brand:{heroMediaMode:"image"}},
  },
  {
    id:"tropical-club",
    name:"Tropical Club",
    category:"Beach Bar",
    layout:"Bottom Tabs",
    description:"Bright tropical color, rounded food tiles and app-like bottom navigation for mobile guests.",
    tags:["tropical","beach","bar","mobile","bottom tabs","photos","colorful"],
    swatches:["#f7f5e8","#0f8f82","#18363a"],
    design:{template:"tiles",styleVariant:"standard",theme:{background:"#f7f5e8",surface:"#fffdf3",card:"#ffffff",text:"#18363a",muted:"#738283",accent:"#ee7f55",accentSecondary:"#9bd4c8",line:"#dce4d9",categoryBackground:"#0f8f82",categoryText:"#ffffff"},typography:{headingFont:"Poppins",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:48,sectionSize:34,itemNameSize:17,descriptionSize:12,priceSize:16},layout:{presentation:"bottom-tabs",density:"comfortable",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"1:1",pricePosition:"inline",cardRadius:24,sectionGap:28,itemGap:14,cardPadding:15},brand:{heroMediaMode:"image"}},
  },
  {
    id:"vegan-garden",
    name:"Vegan Garden",
    category:"Plant Based",
    layout:"Split",
    description:"Fresh botanical split panels for plant-based, wellness and seasonal restaurant menus.",
    tags:["vegan","plant based","healthy","garden","split","photos","organic"],
    swatches:["#eef4e9","#4f7f58","#26352a"],
    design:{template:"split",styleVariant:"standard",theme:{background:"#eef4e9",surface:"#f8fbf5",card:"#ffffff",text:"#26352a",muted:"#738075",accent:"#4f7f58",accentSecondary:"#c7dab8",line:"#d6e1d1",categoryBackground:"#4f7f58",categoryText:"#ffffff"},typography:{headingFont:"Lora",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:56,sectionSize:38,itemNameSize:18,descriptionSize:12,priceSize:16},layout:{density:"spacious",navigationStyle:"minimal",itemImagePosition:"left",itemImageRatio:"4:3",pricePosition:"below",cardRadius:24,sectionGap:38,itemGap:24,cardPadding:22},brand:{heroMediaMode:"image"}},
  },
  {
    id:"seafood-gallery",
    name:"Seafood Gallery",
    category:"Seafood",
    layout:"Gallery",
    description:"Cool ocean tones and large photography for fish bars, coastal kitchens and raw bars.",
    tags:["seafood","fish","coastal","gallery","photos","ocean"],
    swatches:["#eef5f5","#2f7882","#17343a"],
    design:{template:"gallery",styleVariant:"standard",theme:{background:"#eef5f5",surface:"#f8fbfb",card:"#ffffff",text:"#17343a",muted:"#748589",accent:"#2f7882",accentSecondary:"#b8dadd",line:"#d4e3e4",categoryBackground:"#17343a",categoryText:"#ffffff"},typography:{headingFont:"Lora",bodyFont:"Inter",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:56,sectionSize:38,itemNameSize:18,descriptionSize:12,priceSize:16},layout:{density:"spacious",navigationStyle:"underline",itemImagePosition:"top",itemImageRatio:"4:3",pricePosition:"below",cardRadius:20,sectionGap:42,itemGap:22,cardPadding:16},brand:{heroMediaMode:"image"}},
  },
  {
    id:"breakfast-club",
    name:"Breakfast Club",
    category:"Brunch",
    layout:"Tiles",
    description:"Sunny rounded tiles for brunch, breakfast and all-day café menus.",
    tags:["breakfast","brunch","cafe","tiles","photos","friendly"],
    swatches:["#fff6df","#e3a12b","#3a3024"],
    design:{template:"tiles",styleVariant:"standard",theme:{background:"#fff6df",surface:"#fffaf0",card:"#ffffff",text:"#3a3024",muted:"#827665",accent:"#e3a12b",accentSecondary:"#f4d786",line:"#eadcc0",categoryBackground:"#3a3024",categoryText:"#ffffff"},typography:{headingFont:"Poppins",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:46,sectionSize:32,itemNameSize:17,descriptionSize:12,priceSize:16},layout:{density:"comfortable",navigationStyle:"pills",itemImagePosition:"top",itemImageRatio:"1:1",pricePosition:"inline",cardRadius:28,sectionGap:28,itemGap:14,cardPadding:15},brand:{heroMediaMode:"watermark"}},
  },
  {
    id:"taproom-board",
    name:"Taproom Board",
    category:"Beer & Taproom",
    layout:"Ledger",
    description:"Dense tap-list structure with bold names and aligned prices for rotating beer menus.",
    tags:["beer","taproom","bar","ledger","dense","drinks","text"],
    swatches:["#f0eee7","#4f653e","#232821"],
    design:{template:"ledger",styleVariant:"standard",theme:{background:"#f0eee7",surface:"#f7f5ef",card:"#f7f5ef",text:"#232821",muted:"#73776f",accent:"#4f653e",accentSecondary:"#b9c0a8",line:"#cfd1c7",categoryBackground:"#232821",categoryText:"#ffffff"},typography:{headingFont:"Montserrat",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:44,sectionSize:32,itemNameSize:15,descriptionSize:10,priceSize:15},layout:{density:"compact",navigationStyle:"minimal",pricePosition:"inline",cardRadius:0,sectionGap:24,itemGap:8,cardPadding:10},brand:{heroMediaMode:"none"}},
  },
  {
    id:"dessert-magazine",
    name:"Dessert Magazine",
    category:"Dessert Bar",
    layout:"Magazine",
    description:"Asymmetric editorial photography turns a dessert menu into a premium visual spread.",
    tags:["dessert","magazine","photos","editorial","premium","sweet"],
    swatches:["#f9f0ea","#b65d72","#302629"],
    design:{template:"visual",styleVariant:"standard",theme:{background:"#f9f0ea",surface:"#fff9f5",card:"#ffffff",text:"#302629",muted:"#88777c",accent:"#b65d72",accentSecondary:"#e8c8ca",line:"#e5d7d4",categoryBackground:"#302629",categoryText:"#ffffff"},typography:{headingFont:"Playfair Display",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:62,sectionSize:40,itemNameSize:19,descriptionSize:12,priceSize:16},layout:{presentation:"magazine",density:"spacious",navigationStyle:"underline",itemImagePosition:"top",itemImageRatio:"4:3",pricePosition:"inline",cardRadius:2,sectionGap:42,itemGap:22,cardPadding:16},brand:{heroMediaMode:"image"}},
  },
  {
    id:"luxury-steak-story",
    name:"Luxury Steak Story",
    category:"Steakhouse",
    layout:"Photo Story",
    description:"Dark full-bleed steak photography with restrained gold accents for premium dining rooms.",
    tags:["steakhouse","luxury","dark","photo story","photos","premium"],
    swatches:["#11100f","#bd9457","#f3eee5"],
    design:{template:"visual",styleVariant:"standard",theme:{background:"#11100f",surface:"#181614",card:"#11100f",text:"#f3eee5",muted:"#aaa198",accent:"#bd9457",accentSecondary:"#45392b",line:"#38322c",categoryBackground:"#bd9457",categoryText:"#11100f"},typography:{headingFont:"Playfair Display",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:600,bodyWeight:400,itemWeight:700,heroSize:64,sectionSize:38,itemNameSize:22,descriptionSize:13,priceSize:18},layout:{presentation:"photo-story",density:"spacious",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"16:9",pricePosition:"inline",cardRadius:0,sectionGap:24,itemGap:18,cardPadding:22},brand:{heroMediaMode:"image"}},
  },
  {
    id:"blue-launcher",
    name:"Beyond Blue Launcher",
    category:"Contemporary",
    layout:"Launcher",
    description:"A clean Beyond-blue category launcher with strong mobile-app hierarchy and fast navigation.",
    tags:["blue","launcher","mobile","categories","modern","beyond","minimal"],
    swatches:["#f7f5f2","#4974e5","#182238"],
    design:{template:"classic",styleVariant:"standard",theme:{background:"#f7f5f2",surface:"#ffffff",card:"#ffffff",text:"#182238",muted:"#6f7a8d",accent:"#4974e5",accentSecondary:"#dce5ff",line:"#dfe4ec",categoryBackground:"#182238",categoryText:"#ffffff"},typography:{headingFont:"DM Sans",bodyFont:"Inter",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:52,sectionSize:35,itemNameSize:16,descriptionSize:11,priceSize:16},layout:{presentation:"launcher",density:"comfortable",navigationStyle:"minimal",pricePosition:"inline",cardRadius:0,sectionGap:34,itemGap:14,cardPadding:14},brand:{heroMediaMode:"none"}},
  },
  {
    id:"chef-black-editorial",
    name:"Chef Black Editorial",
    category:"Fine Dining",
    layout:"Editorial",
    description:"Near-black paper, ivory typography and restrained spacing for tasting menus and chef counters.",
    tags:["fine dining","chef","editorial","dark","minimal","tasting menu","text"],
    swatches:["#151515","#d8b57a","#f3eee5"],
    design:{template:"editorial",styleVariant:"standard",theme:{background:"#151515",surface:"#191919",card:"#191919",text:"#f3eee5",muted:"#aaa39a",accent:"#d8b57a",accentSecondary:"#3b342a",line:"#35322e",categoryBackground:"#f3eee5",categoryText:"#151515"},typography:{headingFont:"Playfair Display",bodyFont:"DM Sans",numberFont:"Playfair Display",headingWeight:500,bodyWeight:400,itemWeight:600,heroSize:62,sectionSize:42,itemNameSize:17,descriptionSize:11,priceSize:16},layout:{density:"spacious",navigationStyle:"underline",pricePosition:"inline",cardRadius:0,sectionGap:44,itemGap:18,cardPadding:14},brand:{heroMediaMode:"none"}},
  },
  {
    id:"family-pizzeria",
    name:"Family Pizzeria",
    category:"Pizza",
    layout:"Category Covers",
    description:"Bold category blocks and friendly colors make large pizza menus easy to explore on mobile.",
    tags:["pizza","family","casual","covers","mobile","categories","friendly"],
    swatches:["#fff5e7","#d64c3b","#284b3e"],
    design:{template:"classic",styleVariant:"standard",theme:{background:"#fff5e7",surface:"#fffaf2",card:"#ffffff",text:"#2c322d",muted:"#7c7b72",accent:"#d64c3b",accentSecondary:"#efca86",line:"#ead9c5",categoryBackground:"#284b3e",categoryText:"#ffffff"},typography:{headingFont:"Poppins",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:50,sectionSize:34,itemNameSize:17,descriptionSize:12,priceSize:16},layout:{presentation:"category-covers",density:"comfortable",navigationStyle:"minimal",pricePosition:"inline",cardRadius:20,sectionGap:30,itemGap:14,cardPadding:15},brand:{heroMediaMode:"watermark"}},
  },
]);
