import { normalizeMenuDesign } from "./designSchema";

export const PREMIUM_MENU_DESIGNS = Object.freeze([
  {
    id:"heritage-original",
    name:"Heritage Original",
    category:"Classic",
    layout:"Classic",
    description:"Warm hospitality, tactile cards and the original Beyond menu character.",
    tags:["classic","warm","bar","bistro","heritage"],
    swatches:["#f6f4ef","#556b2f","#121212"],
    design:{
      template:"classic",styleVariant:"heritage",
      theme:{background:"#f6f4ef",surface:"#fffdf8",card:"#ffffff",text:"#121212",muted:"#7b756e",accent:"#556b2f",accentSecondary:"#d8c79b",line:"#e5ded2",categoryBackground:"#111111",categoryText:"#ffffff"},
      typography:{headingFont:"Playfair Display",bodyFont:"Inter",numberFont:"Playfair Display",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:46,sectionSize:38,itemNameSize:16,descriptionSize:11,priceSize:16},
      layout:{density:"comfortable",navigationStyle:"pills",pricePosition:"inline",cardRadius:19,sectionGap:20,itemGap:9,cardPadding:15},
      brand:{heroMediaMode:"watermark"},
    },
  },
  {
    id:"atelier-editorial",
    name:"Atelier Editorial",
    category:"Fine Dining",
    layout:"Editorial",
    description:"Magazine-like typography, open space and a refined text-first menu.",
    tags:["editorial","fine dining","luxury","minimal","serif","magazine"],
    swatches:["#f7f5f0","#191919","#a18a62"],
    design:{
      template:"editorial",styleVariant:"standard",
      theme:{background:"#f7f5f0",surface:"#fffefb",card:"#fffefb",text:"#191919",muted:"#77726b",accent:"#8a7250",accentSecondary:"#e7ddcb",line:"#d8d1c6",categoryBackground:"#191919",categoryText:"#ffffff"},
      typography:{headingFont:"Playfair Display",bodyFont:"DM Sans",numberFont:"Playfair Display",headingWeight:500,bodyWeight:400,itemWeight:600,heroSize:62,sectionSize:44,itemNameSize:17,descriptionSize:12,priceSize:16},
      layout:{density:"spacious",navigationStyle:"underline",pricePosition:"inline",cardRadius:0,sectionGap:46,itemGap:18,cardPadding:16},
      brand:{heroMediaMode:"none"},
    },
  },
  {
    id:"noir-gallery",
    name:"Noir Gallery",
    category:"Cocktail Bar",
    layout:"Gallery",
    description:"Cinematic dark photography with oversized image-led menu cards.",
    tags:["dark","luxury","cocktails","night","premium","gallery","photos"],
    swatches:["#11151d","#d0aa68","#f7f5ef"],
    design:{
      template:"gallery",styleVariant:"standard",
      theme:{background:"#11151d",surface:"#161c26",card:"#1b2330",text:"#f7f5ef",muted:"#a9b0bc",accent:"#d0aa68",accentSecondary:"#3b4658",line:"#303948",categoryBackground:"#d0aa68",categoryText:"#11151d"},
      typography:{headingFont:"Playfair Display",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:600,bodyWeight:400,itemWeight:600,heroSize:58,sectionSize:38,itemNameSize:18,descriptionSize:12,priceSize:16},
      layout:{density:"spacious",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"3:2",pricePosition:"below",cardRadius:20,sectionGap:40,itemGap:22,cardPadding:16},
      brand:{heroMediaMode:"image"},
    },
  },
  {
    id:"riviera-split",
    name:"Riviera Split",
    category:"Mediterranean",
    layout:"Split",
    description:"Alternating food photography and copy for a polished Mediterranean story.",
    tags:["mediterranean","seafood","summer","organic","visual","split"],
    swatches:["#f6f1e8","#1f6570","#d49a62"],
    design:{
      template:"split",styleVariant:"standard",
      theme:{background:"#f6f1e8",surface:"#fffaf3",card:"#fffdf9",text:"#16333c",muted:"#738087",accent:"#1f6570",accentSecondary:"#e0b77f",line:"#dedfd8",categoryBackground:"#1f6570",categoryText:"#ffffff"},
      typography:{headingFont:"Lora",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:54,sectionSize:38,itemNameSize:19,descriptionSize:12,priceSize:16},
      layout:{density:"comfortable",navigationStyle:"pills",itemImagePosition:"left",itemImageRatio:"4:3",pricePosition:"below",cardRadius:22,sectionGap:36,itemGap:24,cardPadding:20},
      brand:{heroMediaMode:"image"},
    },
  },
  {
    id:"omakase-minimal",
    name:"Omakase Minimal",
    category:"Japanese",
    layout:"Editorial",
    description:"Quiet Japanese hierarchy with precise spacing, restrained rules and no cards.",
    tags:["japanese","sushi","minimal","quiet","fine dining","editorial"],
    swatches:["#f4f2ed","#20211f","#9a3d32"],
    design:{
      template:"editorial",styleVariant:"standard",
      theme:{background:"#f4f2ed",surface:"#faf9f5",card:"#faf9f5",text:"#20211f",muted:"#777872",accent:"#9a3d32",accentSecondary:"#ddd8cc",line:"#d7d2c8",categoryBackground:"#20211f",categoryText:"#ffffff"},
      typography:{headingFont:"Noto Sans Hebrew",bodyFont:"Inter",numberFont:"Inter",headingWeight:500,bodyWeight:400,itemWeight:600,heroSize:44,sectionSize:31,itemNameSize:15,descriptionSize:11,priceSize:15},
      layout:{density:"spacious",navigationStyle:"underline",pricePosition:"inline",cardRadius:0,sectionGap:40,itemGap:15,cardPadding:12},
      brand:{heroMediaMode:"none"},
    },
  },
  {
    id:"brasserie-ledger",
    name:"Brasserie Ledger",
    category:"European Bistro",
    layout:"Ledger",
    description:"Classic restaurant ledger with disciplined rows and prominent aligned prices.",
    tags:["bistro","restaurant","classic","european","warm","ledger","price list"],
    swatches:["#f8f1e7","#8d3c31","#2c211c"],
    design:{
      template:"ledger",styleVariant:"standard",
      theme:{background:"#f8f1e7",surface:"#fffaf3",card:"#fffdf9",text:"#2c211c",muted:"#786a61",accent:"#8d3c31",accentSecondary:"#d9b494",line:"#d7c6b9",categoryBackground:"#8d3c31",categoryText:"#ffffff"},
      typography:{headingFont:"Merriweather",bodyFont:"DM Sans",numberFont:"Merriweather",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:46,sectionSize:34,itemNameSize:16,descriptionSize:11,priceSize:16},
      layout:{density:"comfortable",navigationStyle:"minimal",pricePosition:"inline",cardRadius:0,sectionGap:30,itemGap:10,cardPadding:12},
      brand:{heroMediaMode:"watermark"},
    },
  },
  {
    id:"gallery-white",
    name:"Gallery White",
    category:"Food Photography",
    layout:"Gallery",
    description:"A bright image-first grid with oversized food photography and clean captions.",
    tags:["visual","photos","food","gallery","modern","white"],
    swatches:["#ffffff","#111111","#ece7df"],
    design:{
      template:"gallery",styleVariant:"standard",
      theme:{background:"#ffffff",surface:"#ffffff",card:"#ffffff",text:"#111111",muted:"#777777",accent:"#111111",accentSecondary:"#ece7df",line:"#e8e8e8",categoryBackground:"#111111",categoryText:"#ffffff"},
      typography:{headingFont:"Playfair Display",bodyFont:"Inter",numberFont:"Inter",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:58,sectionSize:40,itemNameSize:18,descriptionSize:12,priceSize:16},
      layout:{density:"spacious",navigationStyle:"underline",itemImagePosition:"top",itemImageRatio:"1:1",pricePosition:"below",cardRadius:20,sectionGap:44,itemGap:24,cardPadding:16},
      brand:{heroMediaMode:"image"},
    },
  },
  {
    id:"studio-cafe-tiles",
    name:"Studio Café Tiles",
    category:"Café",
    layout:"Tiles",
    description:"Friendly rounded food tiles with strong readability and compact browsing.",
    tags:["cafe","coffee","brunch","modern","friendly","tiles"],
    swatches:["#f5eee7","#745448","#2f2723"],
    design:{
      template:"tiles",styleVariant:"standard",
      theme:{background:"#f5eee7",surface:"#fffaf6",card:"#fffdfa",text:"#2f2723",muted:"#7d7069",accent:"#745448",accentSecondary:"#c8aa91",line:"#e4d7ce",categoryBackground:"#745448",categoryText:"#ffffff"},
      typography:{headingFont:"DM Sans",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:44,sectionSize:32,itemNameSize:16,descriptionSize:12,priceSize:16},
      layout:{density:"comfortable",navigationStyle:"pills",itemImagePosition:"top",itemImageRatio:"1:1",pricePosition:"inline",cardRadius:26,sectionGap:30,itemGap:16,cardPadding:15},
      brand:{heroMediaMode:"watermark"},
    },
  },
  {
    id:"street-bold",
    name:"Street Bold",
    category:"Street Food",
    layout:"Tiles",
    description:"High-energy blocks, bold type and punchy rounded cards for fast casual menus.",
    tags:["street food","burger","pizza","bold","fast casual","tiles"],
    swatches:["#fff7df","#ed5b2d","#181818"],
    design:{
      template:"tiles",styleVariant:"standard",
      theme:{background:"#fff7df",surface:"#fff2c8",card:"#ffffff",text:"#181818",muted:"#6f6658",accent:"#ed5b2d",accentSecondary:"#ffd061",line:"#e8d9b6",categoryBackground:"#181818",categoryText:"#ffffff"},
      typography:{headingFont:"Poppins",bodyFont:"DM Sans",numberFont:"Poppins",headingWeight:800,bodyWeight:500,itemWeight:800,heroSize:52,sectionSize:38,itemNameSize:18,descriptionSize:12,priceSize:17},
      layout:{density:"comfortable",navigationStyle:"pills",itemImagePosition:"top",itemImageRatio:"1:1",pricePosition:"inline",cardRadius:28,sectionGap:28,itemGap:14,cardPadding:15},
      brand:{heroMediaMode:"image"},
    },
  },
  {
    id:"wine-book",
    name:"Wine Book",
    category:"Wine & Spirits",
    layout:"Ledger",
    description:"Dense premium list for vintages, pours and bottles with elegant price rhythm.",
    tags:["wine","spirits","bar","ledger","dense","premium"],
    swatches:["#f2eee6","#6b2234","#2b2926"],
    design:{
      template:"ledger",styleVariant:"standard",
      theme:{background:"#f2eee6",surface:"#f7f3eb",card:"#f7f3eb",text:"#2b2926",muted:"#746e68",accent:"#6b2234",accentSecondary:"#cbb8a3",line:"#cfc5b8",categoryBackground:"#6b2234",categoryText:"#ffffff"},
      typography:{headingFont:"Playfair Display",bodyFont:"DM Sans",numberFont:"Playfair Display",headingWeight:600,bodyWeight:400,itemWeight:600,heroSize:48,sectionSize:34,itemNameSize:15,descriptionSize:10,priceSize:15},
      layout:{density:"compact",navigationStyle:"underline",pricePosition:"inline",cardRadius:0,sectionGap:24,itemGap:8,cardPadding:10},
      brand:{heroMediaMode:"none"},
    },
  },
  {
    id:"coastal-split",
    name:"Coastal Split",
    category:"Beach Restaurant",
    layout:"Split",
    description:"Airy alternating panels with sea-toned accents and large food photography.",
    tags:["coastal","beach","seafood","split","summer","visual"],
    swatches:["#eef6f5","#287b86","#ef9f76"],
    design:{
      template:"split",styleVariant:"standard",
      theme:{background:"#eef6f5",surface:"#f8fcfb",card:"#ffffff",text:"#18383d",muted:"#71858a",accent:"#287b86",accentSecondary:"#bfe1dc",line:"#d3e5e2",categoryBackground:"#287b86",categoryText:"#ffffff"},
      typography:{headingFont:"Lora",bodyFont:"Inter",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:56,sectionSize:38,itemNameSize:18,descriptionSize:12,priceSize:16},
      layout:{density:"spacious",navigationStyle:"minimal",itemImagePosition:"left",itemImageRatio:"3:2",pricePosition:"below",cardRadius:26,sectionGap:38,itemGap:26,cardPadding:22},
      brand:{heroMediaMode:"image"},
    },
  },
  {
    id:"monochrome-editorial",
    name:"Monochrome Editorial",
    category:"Modern Minimal",
    layout:"Editorial",
    description:"Black-and-white editorial menu with oversized headlines and architectural spacing.",
    tags:["minimal","black white","editorial","modern","fashion","fine dining"],
    swatches:["#f7f7f4","#111111","#8a8a84"],
    design:{
      template:"editorial",styleVariant:"standard",
      theme:{background:"#f7f7f4",surface:"#ffffff",card:"#ffffff",text:"#111111",muted:"#777771",accent:"#111111",accentSecondary:"#e3e3de",line:"#cfcfca",categoryBackground:"#111111",categoryText:"#ffffff"},
      typography:{headingFont:"Montserrat",bodyFont:"Inter",numberFont:"Inter",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:64,sectionSize:42,itemNameSize:16,descriptionSize:11,priceSize:15},
      layout:{density:"spacious",navigationStyle:"underline",pricePosition:"inline",cardRadius:0,sectionGap:44,itemGap:17,cardPadding:14},
      brand:{heroMediaMode:"none"},
    },
  },

  /* ===================== PHASE 2 ===================== */
  {
    id:"category-covers",
    name:"Category Covers",
    category:"Modern Restaurant",
    layout:"Category Covers",
    description:"Large touch-first category panels turn navigation into the opening visual experience.",
    tags:["categories","covers","navigation","mobile","modern","touch"],
    swatches:["#f5f1e8","#355c52","#1f2522"],
    design:{
      template:"classic",styleVariant:"standard",
      theme:{background:"#f5f1e8",surface:"#fbf8f1",card:"#ffffff",text:"#1f2522",muted:"#777b75",accent:"#c46b45",accentSecondary:"#e0c9ad",line:"#ddd8cf",categoryBackground:"#355c52",categoryText:"#ffffff"},
      typography:{headingFont:"Lora",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:54,sectionSize:36,itemNameSize:16,descriptionSize:12,priceSize:16},
      layout:{presentation:"category-covers",density:"comfortable",navigationStyle:"minimal",pricePosition:"inline",cardRadius:16,sectionGap:32,itemGap:14,cardPadding:15},
      brand:{heroMediaMode:"watermark"},
    },
  },
  {
    id:"bistro-bottom-tabs",
    name:"Bistro Bottom Tabs",
    category:"Casual Dining",
    layout:"Bottom Tabs",
    description:"App-like mobile browsing keeps every major category reachable from a floating bottom bar.",
    tags:["bottom nav","tabs","mobile","app","bistro","casual"],
    swatches:["#f6f1e8","#9d4235","#2b211d"],
    design:{
      template:"tiles",styleVariant:"standard",
      theme:{background:"#f6f1e8",surface:"#fffaf3",card:"#fffdf9",text:"#2b211d",muted:"#7b6f68",accent:"#9d4235",accentSecondary:"#d8b99b",line:"#e2d7cd",categoryBackground:"#2b211d",categoryText:"#ffffff"},
      typography:{headingFont:"DM Sans",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:44,sectionSize:32,itemNameSize:16,descriptionSize:12,priceSize:16},
      layout:{presentation:"bottom-tabs",density:"comfortable",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"1:1",pricePosition:"inline",cardRadius:22,sectionGap:28,itemGap:14,cardPadding:15},
      brand:{heroMediaMode:"watermark"},
    },
  },
  {
    id:"magazine-spread",
    name:"Magazine Spread",
    category:"Chef Restaurant",
    layout:"Magazine",
    description:"Asymmetric editorial photography creates a restaurant menu that reads like a food magazine.",
    tags:["magazine","editorial","asymmetric","chef","photography","premium"],
    swatches:["#f4f0e9","#b44f36","#171717"],
    design:{
      template:"visual",styleVariant:"standard",
      theme:{background:"#f4f0e9",surface:"#f8f5ef",card:"#ffffff",text:"#171717",muted:"#746f68",accent:"#b44f36",accentSecondary:"#d7c4aa",line:"#d9d2c8",categoryBackground:"#171717",categoryText:"#ffffff"},
      typography:{headingFont:"Playfair Display",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:64,sectionSize:42,itemNameSize:19,descriptionSize:12,priceSize:16},
      layout:{presentation:"magazine",density:"spacious",navigationStyle:"underline",itemImagePosition:"top",itemImageRatio:"4:3",pricePosition:"inline",cardRadius:2,sectionGap:42,itemGap:22,cardPadding:16},
      brand:{heroMediaMode:"image"},
    },
  },
  {
    id:"cocktail-night-cards",
    name:"Cocktail Night Cards",
    category:"Cocktail Bar",
    layout:"Cocktail Cards",
    description:"Tall cinematic drink cards, glowing prices and dark lounge styling for nightlife menus.",
    tags:["cocktails","bar","night","cards","dark","drinks","lounge"],
    swatches:["#0d1017","#e0ae63","#f5efe5"],
    design:{
      template:"visual",styleVariant:"standard",
      theme:{background:"#0d1017",surface:"#121722",card:"#171e2b",text:"#f5efe5",muted:"#9ea7b6",accent:"#e0ae63",accentSecondary:"#2d3a50",line:"#283244",categoryBackground:"#e0ae63",categoryText:"#11151d"},
      typography:{headingFont:"Playfair Display",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:600,bodyWeight:400,itemWeight:600,heroSize:58,sectionSize:36,itemNameSize:20,descriptionSize:12,priceSize:16},
      layout:{presentation:"cocktail-cards",density:"spacious",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"3:2",pricePosition:"inline",cardRadius:24,sectionGap:34,itemGap:22,cardPadding:18},
      brand:{heroMediaMode:"image"},
    },
  },
  {
    id:"photo-story",
    name:"Photo Story",
    category:"Visual Dining",
    layout:"Photo Story",
    description:"Full-bleed food photography becomes the menu, with titles and prices layered directly on each scene.",
    tags:["photo story","full bleed","visual","immersive","food photography","restaurant"],
    swatches:["#161616","#e7bb72","#f8f4ec"],
    design:{
      template:"visual",styleVariant:"standard",
      theme:{background:"#161616",surface:"#1c1c1c",card:"#111111",text:"#f8f4ec",muted:"#b8b1a7",accent:"#e7bb72",accentSecondary:"#45413c",line:"#393633",categoryBackground:"#f8f4ec",categoryText:"#161616"},
      typography:{headingFont:"Playfair Display",bodyFont:"Inter",numberFont:"Inter",headingWeight:700,bodyWeight:400,itemWeight:700,heroSize:62,sectionSize:38,itemNameSize:22,descriptionSize:13,priceSize:18},
      layout:{presentation:"photo-story",density:"spacious",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"16:9",pricePosition:"inline",cardRadius:0,sectionGap:24,itemGap:18,cardPadding:20},
      brand:{heroMediaMode:"image"},
    },
  },
  {
    id:"minimal-grid",
    name:"Minimal Grid",
    category:"Contemporary",
    layout:"Minimal Grid",
    description:"A disciplined two-column text menu with no card chrome and generous modern spacing.",
    tags:["minimal","grid","text","clean","modern","no photos"],
    swatches:["#fafaf8","#1a1a1a","#85857e"],
    design:{
      template:"classic",styleVariant:"standard",
      theme:{background:"#fafaf8",surface:"#ffffff",card:"#ffffff",text:"#1a1a1a",muted:"#85857e",accent:"#1a1a1a",accentSecondary:"#e8e8e3",line:"#deded8",categoryBackground:"#1a1a1a",categoryText:"#ffffff"},
      typography:{headingFont:"Montserrat",bodyFont:"Inter",numberFont:"Inter",headingWeight:700,bodyWeight:400,itemWeight:600,heroSize:54,sectionSize:36,itemNameSize:16,descriptionSize:11,priceSize:15},
      layout:{presentation:"minimal-grid",density:"spacious",navigationStyle:"underline",pricePosition:"inline",cardRadius:0,sectionGap:38,itemGap:16,cardPadding:12},
      brand:{heroMediaMode:"none"},
    },
  },
  {
    id:"fullscreen-category-launcher",
    name:"Fullscreen Category Launcher",
    category:"Experience",
    layout:"Launcher",
    description:"A near full-screen category launcher makes the first interaction feel like a premium mobile app.",
    tags:["launcher","fullscreen","categories","mobile","navigation","experience"],
    swatches:["#f5f3ee","#4974e5","#17213a"],
    design:{
      template:"classic",styleVariant:"standard",
      theme:{background:"#f5f3ee",surface:"#ffffff",card:"#ffffff",text:"#17213a",muted:"#7c8493",accent:"#4974e5",accentSecondary:"#dce4fb",line:"#dfe2e7",categoryBackground:"#17213a",categoryText:"#ffffff"},
      typography:{headingFont:"DM Sans",bodyFont:"Inter",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:50,sectionSize:34,itemNameSize:16,descriptionSize:11,priceSize:16},
      layout:{presentation:"launcher",density:"comfortable",navigationStyle:"minimal",pricePosition:"inline",cardRadius:0,sectionGap:34,itemGap:14,cardPadding:14},
      brand:{heroMediaMode:"none"},
    },
  },
]);

export function applyPremiumMenuDesign(currentDesign,libraryId){
  const entry=PREMIUM_MENU_DESIGNS.find(item=>item.id===libraryId);
  if(!entry)return normalizeMenuDesign(currentDesign);
  const preset=entry.design;
  return normalizeMenuDesign({
    ...currentDesign,
    ...preset,
    theme:{...currentDesign?.theme,...preset.theme},
    typography:{...currentDesign?.typography,...preset.typography},
    layout:{...currentDesign?.layout,...preset.layout},
    brand:{...currentDesign?.brand,...preset.brand},
    badges:{...currentDesign?.badges,...preset.badges},
  });
}
