export const CLINIC_MENU_DESIGNS = Object.freeze([
  {
    id:"clinic-pearl-dental",
    industry:"clinic",
    name:"Pearl Dental",
    category:"Dental",
    layout:"Clean Split",
    description:"Bright, reassuring dental care with crisp white space, calm teal and a confidence-first service layout.",
    tags:["clinic","dental","dentist","orthodontics","clean","medical","teal","trust","bright"],
    swatches:["#f8fcfb","#2d8f91","#17363a"],
    design:{
      template:"split",styleVariant:"standard",
      theme:{background:"#f8fcfb",surface:"#ffffff",card:"#ffffff",text:"#17363a",muted:"#708286",accent:"#2d8f91",accentSecondary:"#cce8e5",line:"#dbe9e7",categoryBackground:"#e7f5f3",categoryText:"#1d6264"},
      typography:{headingFont:"DM Sans",bodyFont:"Inter",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:600,heroSize:50,sectionSize:32,itemNameSize:17,descriptionSize:12,priceSize:15},
      layout:{presentation:"clinic-pearl-dental",density:"spacious",navigationStyle:"pills",itemImagePosition:"right",itemImageRatio:"4:3",pricePosition:"below",cardRadius:22,sectionGap:36,itemGap:18,cardPadding:18},
      brand:{heroMediaMode:"watermark"},
    },
  },
  {
    id:"clinic-aurea-aesthetic",
    industry:"clinic",
    name:"Aurea Aesthetics",
    category:"Aesthetic Clinic",
    layout:"Luxury Editorial",
    description:"Warm cream, stone and restrained gold for premium aesthetics, skincare and cosmetic treatment menus.",
    tags:["clinic","aesthetic","cosmetic","skincare","luxury","beauty","editorial","cream","gold"],
    swatches:["#f4f1ec","#a88455","#2a2a2a"],
    design:{
      template:"gallery",styleVariant:"standard",
      theme:{background:"#f4f1ec",surface:"#fbf9f6",card:"#fffdf9",text:"#2a2a2a",muted:"#81786e",accent:"#a88455",accentSecondary:"#ded2c0",line:"#ddd5ca",categoryBackground:"#2a2a2a",categoryText:"#f8f4ee"},
      typography:{headingFont:"Playfair Display",bodyFont:"Inter",numberFont:"Inter",headingWeight:500,bodyWeight:400,itemWeight:600,heroSize:58,sectionSize:38,itemNameSize:17,descriptionSize:12,priceSize:15},
      layout:{presentation:"clinic-aurea-aesthetic",density:"spacious",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"3:2",pricePosition:"below",cardRadius:4,sectionGap:44,itemGap:22,cardPadding:16},
      brand:{heroMediaMode:"watermark"},
    },
  },
  {
    id:"clinic-sage-medical",
    industry:"clinic",
    name:"Sage Medical",
    category:"Medical Clinic",
    layout:"Trust List",
    description:"Calm blue-green clinical clarity with structured services, strong readability and a reassuring professional tone.",
    tags:["clinic","medical","doctor","healthcare","general practice","calm","green","blue","professional"],
    swatches:["#f3f8f7","#3f746d","#17312e"],
    design:{
      template:"classic",styleVariant:"standard",
      theme:{background:"#f3f8f7",surface:"#ffffff",card:"#ffffff",text:"#17312e",muted:"#70817e",accent:"#3f746d",accentSecondary:"#cbded9",line:"#d8e5e2",categoryBackground:"#3f746d",categoryText:"#ffffff"},
      typography:{headingFont:"DM Sans",bodyFont:"Inter",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:600,heroSize:48,sectionSize:31,itemNameSize:16,descriptionSize:12,priceSize:15},
      layout:{presentation:"clinic-sage-medical",density:"comfortable",navigationStyle:"pills",pricePosition:"inline",cardRadius:14,sectionGap:30,itemGap:10,cardPadding:14},
      brand:{heroMediaMode:"watermark"},
    },
  },
  {
    id:"clinic-kinetic-physio",
    industry:"clinic",
    name:"Kinetic Physio",
    category:"Physiotherapy",
    layout:"Active Cards",
    description:"Fresh blue and energetic green with movement-led cards for physiotherapy, rehabilitation and sports clinics.",
    tags:["clinic","physio","physiotherapy","rehab","sports","movement","active","blue","green"],
    swatches:["#f5f9fc","#246ca6","#7dbb4f"],
    design:{
      template:"tiles",styleVariant:"standard",
      theme:{background:"#f5f9fc",surface:"#ffffff",card:"#ffffff",text:"#16334a",muted:"#6e8292",accent:"#246ca6",accentSecondary:"#b9d89f",line:"#dbe6ee",categoryBackground:"#246ca6",categoryText:"#ffffff"},
      typography:{headingFont:"Montserrat",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:800,bodyWeight:400,itemWeight:700,heroSize:52,sectionSize:34,itemNameSize:17,descriptionSize:12,priceSize:15},
      layout:{presentation:"clinic-kinetic-physio",density:"comfortable",navigationStyle:"pills",itemImagePosition:"top",itemImageRatio:"16:9",pricePosition:"inline",cardRadius:22,sectionGap:32,itemGap:14,cardPadding:16},
      brand:{heroMediaMode:"watermark"},
    },
  },
  {
    id:"clinic-derma-editorial",
    industry:"clinic",
    name:"Derma Editorial",
    category:"Dermatology",
    layout:"Clinical Editorial",
    description:"Quiet dermatologist-led presentation with soft mineral tones, fine rules and precise editorial hierarchy.",
    tags:["clinic","dermatology","skin","derma","medical","editorial","minimal","neutral","precision"],
    swatches:["#f6f4f1","#75675d","#252321"],
    design:{
      template:"editorial",styleVariant:"standard",
      theme:{background:"#f6f4f1",surface:"#fbfaf8",card:"#fbfaf8",text:"#252321",muted:"#7b756f",accent:"#75675d",accentSecondary:"#ddd6cf",line:"#dad4ce",categoryBackground:"#252321",categoryText:"#ffffff"},
      typography:{headingFont:"Lora",bodyFont:"Inter",numberFont:"Inter",headingWeight:600,bodyWeight:400,itemWeight:600,heroSize:54,sectionSize:35,itemNameSize:16,descriptionSize:12,priceSize:15},
      layout:{presentation:"clinic-derma-editorial",density:"spacious",navigationStyle:"underline",pricePosition:"inline",cardRadius:0,sectionGap:42,itemGap:15,cardPadding:12},
      brand:{heroMediaMode:"none"},
    },
  },
  {
    id:"clinic-pediatric-smile",
    industry:"clinic",
    name:"Little Smile",
    category:"Pediatric Clinic",
    layout:"Friendly Tiles",
    description:"Soft color, rounded cards and playful restraint for pediatric medicine and family dental practices.",
    tags:["clinic","pediatric","children","kids","family","dentist","friendly","pastel","playful"],
    swatches:["#fffaf3","#5f91c7","#efb35a"],
    design:{
      template:"tiles",styleVariant:"standard",
      theme:{background:"#fffaf3",surface:"#ffffff",card:"#ffffff",text:"#29445b",muted:"#778897",accent:"#5f91c7",accentSecondary:"#f2c980",line:"#e8e1d8",categoryBackground:"#eaf3fb",categoryText:"#315f88"},
      typography:{headingFont:"Poppins",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:700,bodyWeight:400,itemWeight:600,heroSize:48,sectionSize:32,itemNameSize:16,descriptionSize:12,priceSize:15},
      layout:{presentation:"clinic-pediatric-smile",density:"comfortable",navigationStyle:"pills",itemImagePosition:"top",itemImageRatio:"4:3",pricePosition:"below",cardRadius:28,sectionGap:30,itemGap:14,cardPadding:15},
      brand:{heroMediaMode:"watermark"},
    },
  },
  {
    id:"clinic-obsidian-aesthetic",
    industry:"clinic",
    name:"Obsidian Aesthetics",
    category:"Aesthetic Clinic",
    layout:"Dark Luxury",
    description:"Deep charcoal, warm taupe and cinematic spacing for high-end injectables, laser and cosmetic practices.",
    tags:["clinic","aesthetic","injectables","laser","cosmetic","dark","luxury","premium","cinematic"],
    swatches:["#121313","#b49a82","#f3efe9"],
    design:{
      template:"gallery",styleVariant:"standard",
      theme:{background:"#121313",surface:"#171818",card:"#1c1d1d",text:"#f3efe9",muted:"#aaa29a",accent:"#b49a82",accentSecondary:"#4c4239",line:"#343434",categoryBackground:"#b49a82",categoryText:"#151515"},
      typography:{headingFont:"Playfair Display",bodyFont:"DM Sans",numberFont:"DM Sans",headingWeight:500,bodyWeight:400,itemWeight:600,heroSize:60,sectionSize:38,itemNameSize:17,descriptionSize:12,priceSize:15},
      layout:{presentation:"clinic-obsidian-aesthetic",density:"spacious",navigationStyle:"minimal",itemImagePosition:"top",itemImageRatio:"3:2",pricePosition:"below",cardRadius:16,sectionGap:44,itemGap:22,cardPadding:16},
      brand:{heroMediaMode:"watermark"},
    },
  },
  {
    id:"clinic-ivory-wellness",
    industry:"clinic",
    name:"Ivory Wellness",
    category:"Wellness Clinic",
    layout:"Soft Service List",
    description:"Warm ivory, sage and generous spacing for preventative care, wellness medicine and holistic treatment clinics.",
    tags:["clinic","wellness","preventative","holistic","health","sage","ivory","warm","calm"],
    swatches:["#f8f5ef","#78856a","#3d4037"],
    design:{
      template:"classic",styleVariant:"standard",
      theme:{background:"#f8f5ef",surface:"#fdfbf7",card:"#ffffff",text:"#3d4037",muted:"#7e8178",accent:"#78856a",accentSecondary:"#d9d3c2",line:"#e1ddd3",categoryBackground:"#78856a",categoryText:"#ffffff"},
      typography:{headingFont:"Lora",bodyFont:"Inter",numberFont:"Inter",headingWeight:600,bodyWeight:400,itemWeight:600,heroSize:52,sectionSize:34,itemNameSize:16,descriptionSize:12,priceSize:15},
      layout:{presentation:"clinic-ivory-wellness",density:"spacious",navigationStyle:"pills",pricePosition:"inline",cardRadius:18,sectionGap:34,itemGap:12,cardPadding:16},
      brand:{heroMediaMode:"watermark"},
    },
  },
]);
