import { useEffect, useState } from "react";
import {
  ArrowRight,
  Check,
  ChevronDown,
  Languages,
  Menu as MenuIcon,
  MessageCircle,
  Moon,
  PanelsTopLeft,
  Phone,
  Radio,
  Sparkles,
  Sun,
  UserRound,
  X,
} from "lucide-react";

import { useBeyondLanguage } from "../i18n/BeyondLanguage";
import AuthModal from "../components/AuthModal";
import MyAccount from "../components/MyAccount";
import { supabase } from "../lib/supabaseClient";
import {
  clearMenuBuilderIntent,
  hasMenuBuilderIntent,
  setMenuBuilderIntent,
} from "../lib/menuBuilderIntent";
import beyondLogo from "../assets/beyond-logo-transparent.png";

import "./MenuHome.css";

const menuAccentTextStyle = {
  background: "linear-gradient(100deg, #3975ec, #6073f2)",
  WebkitBackgroundClip: "text",
  backgroundClip: "text",
  color: "transparent",
};

const menuHowCardStyle = {
  background: "#fff7f7",
};

function BeyondPhonePreview({ isHebrew }) {
  return (
    <div className="menu-home-figma-phone" aria-label={isHebrew ? "תצוגת תפריט BEYOND" : "BEYOND menu preview"}>
      <div className="menu-home-figma-island" />
      <div className="menu-home-figma-phone-head">
        <strong>BEYOND MENU</strong>
        <span>{isHebrew ? "ביסטרו איטלקי" : "ITALIAN BISTRO"}</span>
      </div>

      <div className="menu-home-ai-success">
        <Sparkles size={12} />
        <span>{isHebrew ? "נוצר בהצלחה בעזרת AI" : "Successfully Generated by AI"}</span>
      </div>

      <div className="menu-home-phone-category">{isHebrew ? "עיקריות" : "MAINS"}</div>

      <div className="menu-home-phone-menu-row">
        <div><strong>Margherita Pizza</strong><span>{isHebrew ? "מוצרלה טרייה, בזיליקום, רוטב עגבניות" : "Fresh mozzarella, basil, tomato sauce"}</span></div>
        <b>₪38</b>
      </div>
      <div className="menu-home-phone-menu-row">
        <div><strong>Truffle Risotto</strong><span>{isHebrew ? "אורז ארבוריו, כמהין שחורות, פרמזן" : "Arborio rice, black truffle, parmesan"}</span></div>
        <b>₪52</b>
      </div>
      <div className="menu-home-phone-menu-row">
        <div><strong>Classic Tiramisu</strong><span>{isHebrew ? "בישקוטים, אספרסו, מסקרפונה" : "Ladyfingers, espresso, mascarpone"}</span></div>
        <b>₪28</b>
      </div>

      <div className="menu-home-phone-qr-card">
        <div className="menu-home-mini-qr" aria-hidden="true">
          {Array.from({ length: 16 }).map((_, index) => <i key={index} />)}
        </div>
        <strong>{isHebrew ? "סרקו לצפייה בתפריט החי" : "Scan To View Live Menu"}</strong>
      </div>
    </div>
  );
}

function StudioPreview({ isHebrew }) {
  return (
    <div className="menu-home-studio-window">
      <div className="menu-home-window-top">
        <div className="menu-home-window-dots"><i /><i /><i /></div>
        <span>menu.beyond</span>
        <span className="menu-home-window-status"><i />{isHebrew ? "נשמר" : "Saved"}</span>
      </div>
      <div className="menu-home-studio-body">
        <aside>
          <div className="menu-home-studio-brand"><img src={beyondLogo} alt="" /><strong>BEYOND</strong></div>
          <button type="button" className="active"><PanelsTopLeft size={17} />{isHebrew ? "פריטי תפריט" : "Menu items"}</button>
          <button type="button"><MenuIcon size={17} />{isHebrew ? "קטגוריות" : "Categories"}</button>
          <button type="button"><Languages size={17} />{isHebrew ? "שפות" : "Languages"}</button>
        </aside>
        <div className="menu-home-editor">
          <div className="menu-home-editor-heading">
            <div><small>{isHebrew ? "קטגוריה" : "CATEGORY"}</small><h4>{isHebrew ? "קוקטיילים" : "Cocktails"}</h4></div>
            <button type="button">+ {isHebrew ? "הוסף פריט" : "Add item"}</button>
          </div>
          {[{n:"M",t:"Mojito",d:isHebrew?"רום, ליים, נענע וסודה":"Rum, lime, mint & soda",p:"₪42"},{n:"N",t:"Negroni",d:isHebrew?"ג׳ין, ורמוט וקמפרי":"Gin, vermouth & Campari",p:"₪46"},{n:"A",t:"Aperol Spritz",d:isHebrew?"אפרול, פרוסקו וסודה":"Aperol, prosecco & soda",p:"₪44",muted:true}].map(item => (
            <div className={`menu-home-editor-item ${item.muted ? "muted" : ""}`} key={item.t}>
              <div className="menu-home-item-thumb">{item.n}</div><div><strong>{item.t}</strong><span>{item.d}</span></div><b>{item.p}</b>
            </div>
          ))}
        </div>
        <div className="menu-home-phone-preview">
          <div className="menu-home-phone-speaker" /><small>LIVE PREVIEW</small><strong>BEYOND MENU</strong>
          <div className="menu-home-phone-tabs"><span className="active">DRINKS</span><span>FOOD</span></div>
          <div className="menu-home-phone-row"><span>Mojito</span><b>₪42</b></div>
          <div className="menu-home-phone-row"><span>Negroni</span><b>₪46</b></div>
        </div>
      </div>
    </div>
  );
}

function AccessPreview({ isHebrew }) {
  return (
    <div className="menu-home-access-preview">
      <div className="menu-home-table-stand">
        <div className="menu-home-stand-card">
          <img src={beyondLogo} alt="" /><small>BEYOND MENU</small>
          <div className="menu-home-fake-qr">{Array.from({ length: 9 }).map((_, i) => <span key={i} />)}</div>
          <strong>{isHebrew ? "סרקו או הצמידו" : "SCAN OR TAP"}</strong><div className="menu-home-nfc-mark"><Radio size={17} />NFC</div>
        </div>
        <div className="menu-home-stand-base" />
      </div>
      <div className="menu-home-access-phone">
        <div className="menu-home-access-phone-top" /><span className="menu-home-access-check"><Check size={16} /></span>
        <small>{isHebrew ? "התפריט נפתח" : "MENU OPENED"}</small><strong>BEYOND MENU</strong>
        <p>{isHebrew ? "בלי אפליקציה. בלי התחברות." : "No app. No login."}</p>
      </div>
    </div>
  );
}

export default function MenuHomeRefined() {
  const { language, isHebrew, toggleLanguage } = useBeyondLanguage();
  const [navOpen, setNavOpen] = useState(false);
  const [languageOpen, setLanguageOpen] = useState(false);
  const [authOpen, setAuthOpen] = useState(false);
  const [authInitialMode, setAuthInitialMode] = useState("login");
  const [accountOpen, setAccountOpen] = useState(false);
  const [passwordRecovery, setPasswordRecovery] = useState(false);
  const [session, setSession] = useState(null);
  const [authReady, setAuthReady] = useState(false);
  const [profile, setProfile] = useState(null);
  const [emailVerificationStatus, setEmailVerificationStatus] = useState("");
  const [theme, setTheme] = useState(() => {
    try { return window.localStorage.getItem("beyond-theme") === "dark" ? "dark" : "light"; }
    catch { return "light"; }
  });
  const [hasMenuStudioAccess, setHasMenuStudioAccess] = useState(false);
  const [menuStudioSiteId, setMenuStudioSiteId] = useState("");
  const [isMenuStudioAdmin, setIsMenuStudioAdmin] = useState(false);
  const [contactPhone, setContactPhone] = useState("+972-537707072");
  const [contactActionsOpen, setContactActionsOpen] = useState(false);

  useEffect(() => {
    document.documentElement.setAttribute("data-beyond-theme", theme);
    document.documentElement.style.colorScheme = theme;
    try { window.localStorage.setItem("beyond-theme", theme); } catch {}
  }, [theme]);

  useEffect(() => {
    let alive = true;
    async function loadContactPhone() {
      const { data, error } = await supabase.from("app_settings").select("value").eq("key", "contact_phone").maybeSingle();
      if (!alive) return;
      if (error) { console.error("Unable to load contact phone:", error); return; }
      if (data?.value) setContactPhone(data.value);
    }
    loadContactPhone();
    function handleUpdated(event) { if (event.detail?.phone) setContactPhone(event.detail.phone); else loadContactPhone(); }
    window.addEventListener("beyond-contact-phone-updated", handleUpdated);
    return () => { alive = false; window.removeEventListener("beyond-contact-phone-updated", handleUpdated); };
  }, []);

  const contactTel = contactPhone.replace(/[^\d+]/g, "");
  const contactWhatsApp = contactPhone.replace(/\D/g, "");

  function openAuth(mode = "login") { setAuthInitialMode(mode); setAuthOpen(true); setNavOpen(false); }
  function handleStartMenu() {
    if (authReady && session) { clearMenuBuilderIntent(); window.location.assign("/menu-builder"); return; }
    setMenuBuilderIntent(); openAuth("signup");
  }

  useEffect(() => {
    if (!authReady || !session || !hasMenuBuilderIntent()) return;
    clearMenuBuilderIntent(); setAuthOpen(false); window.location.assign("/menu-builder");
  }, [authReady, session?.user?.id]);

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const tokenHash = params.get("token_hash");
    const type = params.get("type");
    if (!tokenHash || type !== "email") return;
    let alive = true;
    async function verifyEmail() {
      setEmailVerificationStatus("verifying");
      try {
        const { data, error } = await supabase.auth.verifyOtp({ token_hash: tokenHash, type: "email" });
        if (!alive) return;
        window.history.replaceState({}, document.title, window.location.pathname);
        if (error) throw error;
        if (data?.session) setSession(data.session);
        setAuthReady(true); setAuthOpen(false); setEmailVerificationStatus("success");
        window.setTimeout(() => { if (alive) setEmailVerificationStatus(""); }, 7000);
      } catch (error) {
        if (!alive) return;
        console.error("Email verification failed:", error);
        window.history.replaceState({}, document.title, window.location.pathname);
        setEmailVerificationStatus("error");
      }
    }
    verifyEmail();
    return () => { alive = false; };
  }, []);

  useEffect(() => {
    let mounted = true;
    supabase.auth.getSession().then(({ data }) => { if (!mounted) return; setSession(data.session || null); setAuthReady(true); });
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, nextSession) => {
      if (!mounted) return;
      setSession(nextSession); setAuthReady(true);
      if (event === "PASSWORD_RECOVERY") { setPasswordRecovery(true); setAccountOpen(true); }
    });
    return () => { mounted = false; subscription.unsubscribe(); };
  }, []);

  useEffect(() => {
    let mounted = true;
    async function loadProfile() {
      if (!session?.user?.id) { setProfile(null); return; }
      const { data, error } = await supabase.from("profiles").select("id, email, full_name, phone, created_at, updated_at").eq("id", session.user.id).single();
      if (!mounted) return;
      if (error) { console.error("Unable to load customer profile:", error); setProfile(null); return; }
      setProfile(data);
    }
    loadProfile();
    return () => { mounted = false; };
  }, [session?.user?.id]);

  useEffect(() => {
    let alive = true;
    async function loadMenuStudioAccess() {
      if (!session?.user?.id) {
        if (alive) { setHasMenuStudioAccess(false); setMenuStudioSiteId(""); setIsMenuStudioAdmin(false); }
        return;
      }
      const [businessResult, siteResult, adminResult] = await Promise.all([
        supabase.from("business_accounts").select("user_id").eq("user_id", session.user.id).maybeSingle(),
        supabase.from("menu_sites").select("id,owner_id").eq("owner_id", session.user.id).order("created_at", { ascending: true }).limit(1).maybeSingle(),
        supabase.from("menu_admins").select("user_id").eq("user_id", session.user.id).maybeSingle(),
      ]);
      if (!alive) return;
      if (businessResult.error || siteResult.error || adminResult.error) {
        console.error("Menu Studio access check failed:", businessResult.error, siteResult.error, adminResult.error);
        setHasMenuStudioAccess(false); setMenuStudioSiteId(""); setIsMenuStudioAdmin(false); return;
      }
      const adminMode = Boolean(adminResult.data);
      const businessGranted = Boolean(businessResult.data && siteResult.data?.id);
      setIsMenuStudioAdmin(adminMode);
      setHasMenuStudioAccess(adminMode || businessGranted);
      setMenuStudioSiteId(adminMode ? "" : businessGranted ? siteResult.data.id : "");
    }
    loadMenuStudioAccess();
    return () => { alive = false; };
  }, [session?.user?.id]);

  async function handleSignOut() { await supabase.auth.signOut(); setProfile(null); setAccountOpen(false); setNavOpen(false); }
  function scrollToSection(id) {
    const element = document.getElementById(id); if (!element) return;
    setNavOpen(false); element.scrollIntoView({ behavior: "smooth", block: "start" });
  }
  function selectLanguage(nextLanguage) {
    if (nextLanguage !== language) toggleLanguage();
    setLanguageOpen(false);
  }

  const accountName = profile?.full_name || profile?.email || session?.user?.user_metadata?.full_name || session?.user?.email || "Customer";
  const accountShortName = String(accountName).split("@")[0].split(" ")[0];
  const avatarUrl = session?.user?.user_metadata?.avatar_url || session?.user?.user_metadata?.picture || "";

  return (
    <main className={`menu-home theme-${theme}`} dir={isHebrew ? "rtl" : "ltr"}>
      {emailVerificationStatus && (
        <div className={`menu-home-verification ${emailVerificationStatus}`} role="status">
          {emailVerificationStatus === "verifying" ? (isHebrew ? "מאמתים את כתובת האימייל..." : "Verifying your email...") : emailVerificationStatus === "success" ? (isHebrew ? "האימייל אומת בהצלחה. ברוכים הבאים ל-BEYOND." : "Email verified successfully. Welcome to BEYOND.") : (isHebrew ? "לא הצלחנו לאמת את הקישור. נסו לבקש קישור חדש." : "We couldn't verify this email link. Please request a new one.")}
        </div>
      )}

      <header className="menu-home-navbar menu-home-navbar-refined">
        <button type="button" className="menu-home-brand" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} aria-label="Beyond home">
          <img src={beyondLogo} alt="Beyond" /><span>BEYOND</span>
        </button>

        <nav className={navOpen ? "menu-home-nav open" : "menu-home-nav"} aria-label="Primary navigation">
          <div className="menu-home-nav-panel-head"><span>{isHebrew ? "ניווט" : "NAVIGATION"}</span><button type="button" onClick={() => setNavOpen(false)} aria-label="Close navigation"><X size={19} /></button></div>
          <button type="button" onClick={() => scrollToSection("product")}>{isHebrew ? "המוצר" : "Product"}</button>
          <button type="button" onClick={() => scrollToSection("how-it-works")}>{isHebrew ? "איך זה עובד" : "How it works"}</button>
          <button type="button" onClick={() => scrollToSection("qr-nfc")}>QR + NFC</button>
          <button type="button" onClick={() => { setNavOpen(false); window.open("/menu/el-puerto", "_blank", "noopener,noreferrer"); }}>{isHebrew ? "תפריט לדוגמה" : "Live demo"}</button>
          <a href="/3DPRINTING#start" onClick={() => setNavOpen(false)}>{isHebrew ? "שליחת פרויקט 3D" : "Submit 3D Project"}</a>
          <a href="/3DPRINTING" onClick={() => setNavOpen(false)}>{isHebrew ? "הדפסת תלת־ממד" : "3D Printing"}</a>
        </nav>

        <div className="menu-home-nav-actions">
          <div className="menu-home-language-wrap">
            <button type="button" className="menu-home-language menu-home-language-figma" onClick={() => setLanguageOpen(current => !current)} aria-expanded={languageOpen}>
              <span>{language === "en" ? "EN" : "עב"}</span><ChevronDown size={13} />
            </button>
            {languageOpen && (
              <div className="menu-home-language-menu">
                <button type="button" className={language === "en" ? "active" : ""} onClick={() => selectLanguage("en")}><span>EN</span><small>English</small></button>
                <button type="button" className={language === "he" ? "active" : ""} onClick={() => selectLanguage("he")}><span>עב</span><small>עברית</small></button>
              </div>
            )}
          </div>

          <button type="button" className="menu-home-theme-toggle" onClick={() => setTheme(current => current === "light" ? "dark" : "light")} aria-label={theme === "light" ? "Switch to dark mode" : "Switch to light mode"}>
            {theme === "light" ? <Moon size={17} /> : <Sun size={17} />}
          </button>

          {authReady && session && hasMenuStudioAccess ? (
            <button type="button" className="menu-home-studio-button" onClick={() => window.open(isMenuStudioAdmin ? "/menu-studio" : `/menu-studio?site=${menuStudioSiteId}`, "beyond-menu-studio", "width=1440,height=950,noopener,noreferrer")}>
              <span className="menu-home-studio-full">Menu Studio</span><span className="menu-home-studio-short">Studio</span>
            </button>
          ) : null}

          {authReady && session ? (
            <button type="button" className="menu-home-account menu-home-account-figma" onClick={() => setAccountOpen(true)} aria-label="My account">
              <span className="menu-home-account-name">{accountShortName}</span>
              <b className="menu-home-account-avatar">
                {avatarUrl ? <img src={avatarUrl} alt="" /> : accountName.charAt(0).toUpperCase()}
              </b>
            </button>
          ) : (
            <button type="button" className="menu-home-login menu-home-login-refined" onClick={() => openAuth("login")}><UserRound size={16} /><span>{isHebrew ? "התחברות" : "Log in"}</span></button>
          )}

          <button type="button" className="menu-home-mobile-toggle menu-home-hamburger-always" onClick={() => setNavOpen(current => !current)} aria-label={navOpen ? "Close navigation" : "Open navigation"} aria-expanded={navOpen}>
            {navOpen ? <X size={21} /> : <MenuIcon size={21} />}
          </button>
        </div>
      </header>

      <section className="menu-home-hero" id="product">
        <div className="menu-home-hero-copy">
          <div className="menu-home-kicker"><Sparkles size={15} />{isHebrew ? "הדרך הפשוטה לתפריט דיגיטלי" : "THE SIMPLE WAY TO GO DIGITAL"}</div>
          <h1>{isHebrew ? <>יוצרים תפריט דיגיטלי<span>בדקות.</span></> : <>Create your digital menu<span>in minutes.</span></>}</h1>
          <p>{isHebrew ? "בנו, עדכנו ושתפו את תפריט המסעדה ממקום אחד. QR, NFC, מספר שפות ועדכונים מיידיים — בלי אפליקציה ללקוח." : "Build, update and share your restaurant menu from one place. QR, NFC, multiple languages and instant updates — with no app for your customers."}</p>
          <div className="menu-home-hero-actions">
            <button type="button" className="menu-home-primary" onClick={handleStartMenu}>{isHebrew ? "יצירת תפריט בחינם" : "Create My Menu Free"}<ArrowRight size={18} /></button>
            <button type="button" className="menu-home-secondary" onClick={() => window.open("/menu/el-puerto", "_blank", "noopener,noreferrer")}>{isHebrew ? "צפייה בתפריט לדוגמה" : "View Live Demo"}</button>
          </div>
          <div className="menu-home-hero-notes">
            <span><Check size={15} />{isHebrew ? "ללא אפליקציה" : "No app required"}</span><span><Check size={15} />QR + NFC</span><span><Check size={15} />{isHebrew ? "עדכון בכל רגע" : "Update anytime"}</span>
          </div>
        </div>
        <div className="menu-home-hero-visual menu-home-phone-hero-visual"><BeyondPhonePreview isHebrew={isHebrew} /></div>
      </section>

      <section className="menu-home-how" id="how-it-works">
        <div className="menu-home-section-heading"><div style={{ gridColumn: "1 / -1" }}><div className="menu-home-kicker"><Sparkles size={15} />{isHebrew ? "איך זה עובד" : "HOW IT WORKS"}</div><h2>{isHebrew ? <>מהרעיון לשולחן ב-<span style={{ color: "#6073f2" }}>3</span> צעדים.</> : <>From idea to table in <span style={{ color: "#6073f2" }}>3</span> steps.</>}</h2></div></div>
        <div className="menu-home-step-grid">
          <article style={menuHowCardStyle}><div className="menu-home-step-number" style={{ ...menuAccentTextStyle, marginBottom: "36px", fontSize: "38px", fontWeight: 850, letterSpacing: "-0.04em", lineHeight: 1 }}>01</div><h3>{isHebrew ? "יוצרים את התפריט" : "Create your menu"}</h3><p>{isHebrew ? "מוסיפים קטגוריות, מנות, מחירים, תיאורים ותמונות." : "Add categories, items, prices, descriptions and images."}</p></article>
          <article style={menuHowCardStyle}><div className="menu-home-step-number" style={{ ...menuAccentTextStyle, marginBottom: "36px", fontSize: "38px", fontWeight: 850, letterSpacing: "-0.04em", lineHeight: 1 }}>02</div><h3>{isHebrew ? "מתאימים למותג" : "Make it yours"}</h3><p>{isHebrew ? "מתאימים את השפה, התוכן והנראות למסעדה שלכם." : "Adjust the language, content and look to fit your restaurant."}</p></article>
          <article style={menuHowCardStyle}><div className="menu-home-step-number" style={{ ...menuAccentTextStyle, marginBottom: "36px", fontSize: "38px", fontWeight: 850, letterSpacing: "-0.04em", lineHeight: 1 }}>03</div><h3>{isHebrew ? "משתפים" : "Share it"}</h3><p>{isHebrew ? "הלקוחות סורקים QR או מצמידים את הטלפון ל-NFC והתפריט נפתח." : "Customers scan the QR or tap NFC and your menu opens instantly."}</p></article>
        </div>
      </section>

      <section className="menu-home-studio-section">
        <div className="menu-home-studio-copy">
          <div className="menu-home-kicker"><PanelsTopLeft size={15} />MENU MANAGEMENT</div>
          <h2>{isHebrew ? "כל מה שצריך כדי לנהל תפריט. במקום אחד." : <>Everything you need to manage <span style={{ color: "#6073f2" }}>your menu</span>. In one place.</>}</h2>
          <p>{isHebrew ? "שינוי מחיר, הוספת מנה או עדכון תיאור לא צריכים לחכות להדפסה מחדש. עורכים פעם אחת והשינוי מתעדכן בתפריט." : "Changing a price, adding an item or updating a description should not require a reprint. Edit once and your menu updates."}</p>
          <div className="menu-home-feature-list"><span><Check size={16} />{isHebrew ? "עריכת מחירים ומנות" : "Edit prices and items"}</span><span><Check size={16} />{isHebrew ? "קטגוריות מסודרות" : "Organized categories"}</span><span><Check size={16} />{isHebrew ? "מספר שפות" : "Multiple languages"}</span><span><Check size={16} />{isHebrew ? "תצוגה מקדימה בזמן אמת" : "Live preview"}</span></div>
        </div>
        <StudioPreview isHebrew={isHebrew} />
      </section>
      <section className="menu-home-access-section" id="qr-nfc">
        <AccessPreview isHebrew={isHebrew} />
        <div className="menu-home-access-copy"><div className="menu-home-kicker"><Radio size={15} />{isHebrew ? "מעמדים מודפסים בתלת־ממד" : "3D PRINTED STANDS"}</div><h2>{isHebrew ? "מעמדי תלת־ממד בהתאמה אישית, שנבנו למותג שלכם." : <>Custom <span style={{ color: "#6073f2" }}>3D</span> printed stands, made for your brand.</>}</h2><p>{isHebrew ? "כל מעמד מודפס בתלת־ממד ומותאם לסגנון, לצבעים וללוגו של המסעדה שלכם — כדי שירגיש כמו חלק טבעי מהמותג." : "Each stand is 3D printed and tailored to match your restaurant’s style, colors and logo — so it feels like part of your brand."}</p><div className="menu-home-access-points"><span><Check size={16} />{isHebrew ? "מותאם לסגנון המותג שלכם" : "Tailored to your brand style"}</span><span><Check size={16} />{isHebrew ? "לוגו וצבעים מותאמים לכל לקוח" : "Logo and colors customized for each customer"}</span><span><Check size={16} />{isHebrew ? "QR + NFC משולבים במעמד אחד" : "QR + NFC integrated in one stand"}</span></div></div>
      </section>

      <section className="menu-home-final">
        <div><span>BEYOND MENU</span><h2>{isHebrew ? "התפריט הבא שלכם יכול להיות באוויר היום." : "Your next menu can be live today."}</h2><p>{isHebrew ? "מתחילים פשוט, מעדכנים מתי שרוצים ונותנים ללקוחות חוויה ברורה ומהירה." : "Start simple, update whenever you need, and give customers a clear, fast experience."}</p></div>
        <div className="menu-home-contact-action-wrap">
          <button type="button" className={`menu-home-primary menu-home-contact-trigger ${contactActionsOpen ? "is-open" : ""}`} onClick={() => setContactActionsOpen(current => !current)} aria-expanded={contactActionsOpen}>{isHebrew ? "צור קשר" : "Contact Us"}</button>
          {contactActionsOpen && (
            <div className="menu-home-contact-panel">
              <a href={`tel:${contactTel}`} onClick={() => setContactActionsOpen(false)}><Phone size={17} /><span><small>{isHebrew ? "טלפון" : "PHONE"}</small><strong>{isHebrew ? "התקשרו עכשיו" : "Call now"}</strong></span></a>
              <a href={`https://wa.me/${contactWhatsApp}`} target="_blank" rel="noopener noreferrer" onClick={() => setContactActionsOpen(false)}><MessageCircle size={17} /><span><small>WHATSAPP</small><strong>{isHebrew ? "פתחו צ׳אט" : "Start a chat"}</strong></span></a>
            </div>
          )}
        </div>
      </section>

      <footer className="menu-home-footer">
        <div className="menu-home-footer-brand"><img src={beyondLogo} alt="" /><strong>BEYOND</strong></div>
        <p>{isHebrew ? "תפריטים דיגיטליים למסעדות, בתי קפה וברים." : "Digital menus for restaurants, cafés and bars."}</p>
        <div className="menu-home-footer-links"><button type="button" onClick={handleStartMenu}>{isHebrew ? "יצירת תפריט" : "Menu Builder"}</button><button type="button" onClick={() => window.open("/menu/el-puerto", "_blank", "noopener,noreferrer")}>{isHebrew ? "דוגמה" : "Live Demo"}</button><a href="/3DPRINTING">3D Printing</a></div>
        <small>© 2026 BEYOND</small>
      </footer>

      <AuthModal open={authOpen} initialMode={authInitialMode} onClose={() => setAuthOpen(false)} />
      <MyAccount open={accountOpen} onClose={() => setAccountOpen(false)} session={session} profile={profile} onProfileUpdated={nextProfile => setProfile(nextProfile)} passwordRecovery={passwordRecovery} onPasswordRecoveryComplete={() => setPasswordRecovery(false)} onSignOut={handleSignOut} />
    </main>
  );
}