export const MENU_CONTENT_STUDIO_UI = {
  en: {
    interfaceLanguage:"Interface language", contentLanguage:"Menu content", backSetup:"Back to setup", workspace:"Menu workspace",
    content:"Content", design:"Design", preview:"Preview", publish:"Publish",
    saved:"Saved locally", saving:"Saving…", saveError:"Could not save",
    contentEyebrow:"CONTENT", menuStructure:"Menu structure", addCategory:"Add category", categories:"Categories", restaurantDetails:"Restaurant details",
    addItem:"Add item", noPrice:"No price", items:(count)=>`${count} ${count === 1 ? "item" : "items"}`,
    livePreview:"LIVE PREVIEW", previewHint:"Select content on the left to edit", selectedDesign:"Selected design", mobile:"Mobile",
    restaurantEyebrow:"RESTAURANT", menuDetails:"Menu details", restaurantHelp:"These details appear throughout the customer menu.", restaurantName:"Restaurant name", subtitle:"Subtitle",
    designApplied:"Design fit applied", designAppliedHint:(name)=>`${name || "The recommended design"} was selected from your onboarding answers. Design Studio is where you refine colors, type and layout.`,
    categoryEyebrow:"CATEGORY", categoryHelp:"Edit the category customers use to navigate the menu.", categoryName:"Category name", visible:"Visible in menu", visibleCategory:"Customers can browse this category", addItemCategory:"Add item to category", deleteCategory:"Delete category",
    itemEyebrow:"MENU ITEM", itemHelp:"Edit the content customers see. Design is handled separately.", itemName:"Item name", description:"Description", price:"Price", imageUrl:"Image URL", tempDev:"temporary dev input", visibleItem:"Customers can see this item", deleteItem:"Delete item",
    updatesLive:"Content updates live", draftKept:"Your draft is kept in this development session.", continueDesign:"Continue to Design",
    newCategory:"New category", newItem:"New item", newDescription:"Add a short description",
  },
  he: {
    interfaceLanguage:"שפת הממשק", contentLanguage:"שפת תוכן התפריט", backSetup:"חזרה להגדרה", workspace:"סביבת עבודת התפריט",
    content:"תוכן", design:"עיצוב", preview:"תצוגה מקדימה", publish:"פרסום",
    saved:"נשמר מקומית", saving:"שומר…", saveError:"לא ניתן לשמור",
    contentEyebrow:"תוכן", menuStructure:"מבנה התפריט", addCategory:"הוספת קטגוריה", categories:"קטגוריות", restaurantDetails:"פרטי המסעדה",
    addItem:"הוספת פריט", noPrice:"ללא מחיר", items:(count)=>`${count} פריטים`,
    livePreview:"תצוגה חיה", previewHint:"בחרו תוכן משמאל כדי לערוך", selectedDesign:"עיצוב נבחר", mobile:"נייד",
    restaurantEyebrow:"מסעדה", menuDetails:"פרטי התפריט", restaurantHelp:"הפרטים האלה מופיעים לאורך תפריט הלקוחות.", restaurantName:"שם המסעדה", subtitle:"כותרת משנה",
    designApplied:"ההתאמה העיצובית הוחלה", designAppliedHint:(name)=>`${name || "העיצוב המומלץ"} נבחר לפי תשובות ההיכרות שלכם. ב-Design Studio תוכלו לדייק צבעים, טיפוגרפיה ופריסה.`,
    categoryEyebrow:"קטגוריה", categoryHelp:"ערכו את הקטגוריה שבה הלקוחות משתמשים כדי לנווט בתפריט.", categoryName:"שם הקטגוריה", visible:"מוצג בתפריט", visibleCategory:"לקוחות יכולים לגלוש בקטגוריה", addItemCategory:"הוספת פריט לקטגוריה", deleteCategory:"מחיקת קטגוריה",
    itemEyebrow:"פריט תפריט", itemHelp:"ערכו את התוכן שהלקוחות רואים. העיצוב מטופל בנפרד.", itemName:"שם הפריט", description:"תיאור", price:"מחיר", imageUrl:"כתובת תמונה", tempDev:"שדה זמני לפיתוח", visibleItem:"לקוחות יכולים לראות את הפריט", deleteItem:"מחיקת פריט",
    updatesLive:"התוכן מתעדכן בזמן אמת", draftKept:"הטיוטה נשמרת בסשן הפיתוח הזה.", continueDesign:"המשך לעיצוב",
    newCategory:"קטגוריה חדשה", newItem:"פריט חדש", newDescription:"הוסיפו תיאור קצר",
  },
  ar: {
    interfaceLanguage:"لغة الواجهة", contentLanguage:"لغة محتوى القائمة", backSetup:"العودة للإعداد", workspace:"مساحة عمل القائمة",
    content:"المحتوى", design:"التصميم", preview:"المعاينة", publish:"النشر",
    saved:"تم الحفظ محلياً", saving:"جارٍ الحفظ…", saveError:"تعذر الحفظ",
    contentEyebrow:"المحتوى", menuStructure:"هيكل القائمة", addCategory:"إضافة فئة", categories:"الفئات", restaurantDetails:"تفاصيل المطعم",
    addItem:"إضافة صنف", noPrice:"بدون سعر", items:(count)=>`${count} أصناف`,
    livePreview:"معاينة مباشرة", previewHint:"اختاروا المحتوى من اليسار لتعديله", selectedDesign:"التصميم المختار", mobile:"هاتف",
    restaurantEyebrow:"المطعم", menuDetails:"تفاصيل القائمة", restaurantHelp:"تظهر هذه التفاصيل في أنحاء قائمة الزبائن.", restaurantName:"اسم المطعم", subtitle:"العنوان الفرعي",
    designApplied:"تم تطبيق ملاءمة التصميم", designAppliedHint:(name)=>`${name || "التصميم المقترح"} تم اختياره بناءً على إجابات الإعداد. داخل Design Studio يمكنكم ضبط الألوان والخطوط والتخطيط.`,
    categoryEyebrow:"فئة", categoryHelp:"عدّلوا الفئة التي يستخدمها الزبائن للتنقل في القائمة.", categoryName:"اسم الفئة", visible:"ظاهر في القائمة", visibleCategory:"يمكن للزبائن تصفح هذه الفئة", addItemCategory:"إضافة صنف إلى الفئة", deleteCategory:"حذف الفئة",
    itemEyebrow:"صنف", itemHelp:"عدّلوا المحتوى الذي يراه الزبائن. التصميم تتم إدارته بشكل منفصل.", itemName:"اسم الصنف", description:"الوصف", price:"السعر", imageUrl:"رابط الصورة", tempDev:"حقل تطوير مؤقت", visibleItem:"يمكن للزبائن رؤية هذا الصنف", deleteItem:"حذف الصنف",
    updatesLive:"المحتوى يتحدث مباشرة", draftKept:"المسودة محفوظة في جلسة التطوير الحالية.", continueDesign:"المتابعة إلى التصميم",
    newCategory:"فئة جديدة", newItem:"صنف جديد", newDescription:"أضيفوا وصفاً قصيراً",
  },
};
